// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "trustkeeper-go/app/service/chains_query/pkg/endpoint"
	pb "trustkeeper-go/app/service/chains_query/pkg/grpc/pb"

	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	bitcoincoreBlock  grpc.Handler
	queryOmniProperty grpc.Handler
	eRC20TokenInfo    grpc.Handler
	constructTxBTC    grpc.Handler
	sendBTCTx         grpc.Handler
	constructTxOmni   grpc.Handler
	constructTxETH    grpc.Handler
	sendETHTx         grpc.Handler
	constructTxERC20  grpc.Handler
	queryBalance      grpc.Handler
	walletValidate    grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.ChainsQueryServer {
	return &grpcServer{
		bitcoincoreBlock:  makeBitcoincoreBlockHandler(endpoints, options["BitcoincoreBlock"]),
		constructTxBTC:    makeConstructTxBTCHandler(endpoints, options["ConstructTxBTC"]),
		constructTxERC20:  makeConstructTxERC20Handler(endpoints, options["ConstructTxERC20"]),
		constructTxETH:    makeConstructTxETHHandler(endpoints, options["ConstructTxETH"]),
		constructTxOmni:   makeConstructTxOmniHandler(endpoints, options["ConstructTxOmni"]),
		eRC20TokenInfo:    makeERC20TokenInfoHandler(endpoints, options["ERC20TokenInfo"]),
		queryBalance:      makeQueryBalanceHandler(endpoints, options["QueryBalance"]),
		queryOmniProperty: makeQueryOmniPropertyHandler(endpoints, options["QueryOmniProperty"]),
		sendBTCTx:         makeSendBTCTxHandler(endpoints, options["SendBTCTx"]),
		sendETHTx:         makeSendETHTxHandler(endpoints, options["SendETHTx"]),
		walletValidate:    makeWalletValidateHandler(endpoints, options["WalletValidate"]),
	}
}
