// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet_key.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GenerateMnemonicRequest struct {
	Namespaceid          string   `protobuf:"bytes,1,opt,name=namespaceid" json:"namespaceid,omitempty"`
	Bip44Ids             []int32  `protobuf:"varint,2,rep,packed,name=bip44ids" json:"bip44ids,omitempty"`
	Bip44AccountSize     int32    `protobuf:"varint,3,opt,name=bip44accountSize" json:"bip44accountSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateMnemonicRequest) Reset()         { *m = GenerateMnemonicRequest{} }
func (m *GenerateMnemonicRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateMnemonicRequest) ProtoMessage()    {}
func (*GenerateMnemonicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_key_0780d30c4c594c5d, []int{0}
}
func (m *GenerateMnemonicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateMnemonicRequest.Unmarshal(m, b)
}
func (m *GenerateMnemonicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateMnemonicRequest.Marshal(b, m, deterministic)
}
func (dst *GenerateMnemonicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateMnemonicRequest.Merge(dst, src)
}
func (m *GenerateMnemonicRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateMnemonicRequest.Size(m)
}
func (m *GenerateMnemonicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateMnemonicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateMnemonicRequest proto.InternalMessageInfo

func (m *GenerateMnemonicRequest) GetNamespaceid() string {
	if m != nil {
		return m.Namespaceid
	}
	return ""
}

func (m *GenerateMnemonicRequest) GetBip44Ids() []int32 {
	if m != nil {
		return m.Bip44Ids
	}
	return nil
}

func (m *GenerateMnemonicRequest) GetBip44AccountSize() int32 {
	if m != nil {
		return m.Bip44AccountSize
	}
	return 0
}

type Bip44AccountKey struct {
	Account              int32    `protobuf:"varint,1,opt,name=account" json:"account,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bip44AccountKey) Reset()         { *m = Bip44AccountKey{} }
func (m *Bip44AccountKey) String() string { return proto.CompactTextString(m) }
func (*Bip44AccountKey) ProtoMessage()    {}
func (*Bip44AccountKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_key_0780d30c4c594c5d, []int{1}
}
func (m *Bip44AccountKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bip44AccountKey.Unmarshal(m, b)
}
func (m *Bip44AccountKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bip44AccountKey.Marshal(b, m, deterministic)
}
func (dst *Bip44AccountKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bip44AccountKey.Merge(dst, src)
}
func (m *Bip44AccountKey) XXX_Size() int {
	return xxx_messageInfo_Bip44AccountKey.Size(m)
}
func (m *Bip44AccountKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Bip44AccountKey.DiscardUnknown(m)
}

var xxx_messageInfo_Bip44AccountKey proto.InternalMessageInfo

func (m *Bip44AccountKey) GetAccount() int32 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *Bip44AccountKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Bip44ThirdXpubsForChain struct {
	Chain                int32              `protobuf:"varint,1,opt,name=chain" json:"chain,omitempty"`
	Xpubs                []*Bip44AccountKey `protobuf:"bytes,2,rep,name=xpubs" json:"xpubs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Bip44ThirdXpubsForChain) Reset()         { *m = Bip44ThirdXpubsForChain{} }
func (m *Bip44ThirdXpubsForChain) String() string { return proto.CompactTextString(m) }
func (*Bip44ThirdXpubsForChain) ProtoMessage()    {}
func (*Bip44ThirdXpubsForChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_key_0780d30c4c594c5d, []int{2}
}
func (m *Bip44ThirdXpubsForChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bip44ThirdXpubsForChain.Unmarshal(m, b)
}
func (m *Bip44ThirdXpubsForChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bip44ThirdXpubsForChain.Marshal(b, m, deterministic)
}
func (dst *Bip44ThirdXpubsForChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bip44ThirdXpubsForChain.Merge(dst, src)
}
func (m *Bip44ThirdXpubsForChain) XXX_Size() int {
	return xxx_messageInfo_Bip44ThirdXpubsForChain.Size(m)
}
func (m *Bip44ThirdXpubsForChain) XXX_DiscardUnknown() {
	xxx_messageInfo_Bip44ThirdXpubsForChain.DiscardUnknown(m)
}

var xxx_messageInfo_Bip44ThirdXpubsForChain proto.InternalMessageInfo

func (m *Bip44ThirdXpubsForChain) GetChain() int32 {
	if m != nil {
		return m.Chain
	}
	return 0
}

func (m *Bip44ThirdXpubsForChain) GetXpubs() []*Bip44AccountKey {
	if m != nil {
		return m.Xpubs
	}
	return nil
}

type GenerateMnemonicReply struct {
	Chainsxpubs          []*Bip44ThirdXpubsForChain `protobuf:"bytes,1,rep,name=chainsxpubs" json:"chainsxpubs,omitempty"`
	Version              string                     `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GenerateMnemonicReply) Reset()         { *m = GenerateMnemonicReply{} }
func (m *GenerateMnemonicReply) String() string { return proto.CompactTextString(m) }
func (*GenerateMnemonicReply) ProtoMessage()    {}
func (*GenerateMnemonicReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_key_0780d30c4c594c5d, []int{3}
}
func (m *GenerateMnemonicReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateMnemonicReply.Unmarshal(m, b)
}
func (m *GenerateMnemonicReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateMnemonicReply.Marshal(b, m, deterministic)
}
func (dst *GenerateMnemonicReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateMnemonicReply.Merge(dst, src)
}
func (m *GenerateMnemonicReply) XXX_Size() int {
	return xxx_messageInfo_GenerateMnemonicReply.Size(m)
}
func (m *GenerateMnemonicReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateMnemonicReply.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateMnemonicReply proto.InternalMessageInfo

func (m *GenerateMnemonicReply) GetChainsxpubs() []*Bip44ThirdXpubsForChain {
	if m != nil {
		return m.Chainsxpubs
	}
	return nil
}

func (m *GenerateMnemonicReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*GenerateMnemonicRequest)(nil), "pb.GenerateMnemonicRequest")
	proto.RegisterType((*Bip44AccountKey)(nil), "pb.Bip44AccountKey")
	proto.RegisterType((*Bip44ThirdXpubsForChain)(nil), "pb.Bip44ThirdXpubsForChain")
	proto.RegisterType((*GenerateMnemonicReply)(nil), "pb.GenerateMnemonicReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletKeyClient is the client API for WalletKey service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletKeyClient interface {
	GenerateMnemonic(ctx context.Context, in *GenerateMnemonicRequest, opts ...grpc.CallOption) (*GenerateMnemonicReply, error)
}

type walletKeyClient struct {
	cc *grpc.ClientConn
}

func NewWalletKeyClient(cc *grpc.ClientConn) WalletKeyClient {
	return &walletKeyClient{cc}
}

func (c *walletKeyClient) GenerateMnemonic(ctx context.Context, in *GenerateMnemonicRequest, opts ...grpc.CallOption) (*GenerateMnemonicReply, error) {
	out := new(GenerateMnemonicReply)
	err := c.cc.Invoke(ctx, "/pb.WalletKey/GenerateMnemonic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletKeyServer is the server API for WalletKey service.
type WalletKeyServer interface {
	GenerateMnemonic(context.Context, *GenerateMnemonicRequest) (*GenerateMnemonicReply, error)
}

func RegisterWalletKeyServer(s *grpc.Server, srv WalletKeyServer) {
	s.RegisterService(&_WalletKey_serviceDesc, srv)
}

func _WalletKey_GenerateMnemonic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateMnemonicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletKeyServer).GenerateMnemonic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletKey/GenerateMnemonic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletKeyServer).GenerateMnemonic(ctx, req.(*GenerateMnemonicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletKey_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.WalletKey",
	HandlerType: (*WalletKeyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateMnemonic",
			Handler:    _WalletKey_GenerateMnemonic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet_key.proto",
}

func init() { proto.RegisterFile("wallet_key.proto", fileDescriptor_wallet_key_0780d30c4c594c5d) }

var fileDescriptor_wallet_key_0780d30c4c594c5d = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x55, 0x5a, 0x05, 0xe8, 0x75, 0x20, 0x32, 0xa0, 0x86, 0xb2, 0x44, 0x99, 0x02, 0x43, 0x86,
	0xd2, 0xb5, 0x03, 0x20, 0x81, 0x04, 0x62, 0x31, 0x48, 0x45, 0x2c, 0xc8, 0x49, 0x4e, 0xaa, 0xd5,
	0xd4, 0x36, 0x71, 0x02, 0x84, 0x95, 0x1f, 0x47, 0x76, 0xd2, 0xaa, 0x6a, 0x60, 0xbb, 0xf7, 0xfc,
	0xfc, 0xee, 0xdd, 0x1d, 0x78, 0x9f, 0x2c, 0xcf, 0xb1, 0x7c, 0x5b, 0x62, 0x1d, 0xab, 0x42, 0x96,
	0x92, 0xf4, 0x54, 0x12, 0xfe, 0x38, 0x30, 0xba, 0x43, 0x81, 0x05, 0x2b, 0xf1, 0x51, 0xe0, 0x4a,
	0x0a, 0x9e, 0x52, 0x7c, 0xaf, 0x50, 0x97, 0x24, 0x80, 0xa1, 0x60, 0x2b, 0xd4, 0x8a, 0xa5, 0xc8,
	0x33, 0xdf, 0x09, 0x9c, 0x68, 0x40, 0xb7, 0x29, 0x32, 0x86, 0x83, 0x84, 0xab, 0xe9, 0x94, 0x67,
	0xda, 0xef, 0x05, 0xfd, 0xc8, 0xa5, 0x1b, 0x4c, 0x2e, 0xc0, 0xb3, 0x35, 0x4b, 0x53, 0x59, 0x89,
	0xf2, 0x89, 0x7f, 0xa3, 0xdf, 0x0f, 0x9c, 0xc8, 0xa5, 0x1d, 0x3e, 0x9c, 0xc1, 0xe1, 0xb5, 0xe1,
	0xae, 0x1a, 0xee, 0x01, 0x6b, 0xe2, 0xc3, 0x7e, 0xab, 0xb0, 0x8d, 0x5d, 0xba, 0x86, 0xc4, 0x83,
	0xfe, 0x12, 0x6b, 0xbf, 0x67, 0xe3, 0x98, 0x32, 0x7c, 0x85, 0x91, 0xfd, 0xfe, 0xbc, 0xe0, 0x45,
	0xf6, 0xa2, 0xaa, 0x44, 0xdf, 0xca, 0xe2, 0x66, 0xc1, 0xb8, 0x20, 0xc7, 0xe0, 0xa6, 0xa6, 0x68,
	0x4d, 0x1a, 0x40, 0xce, 0xc1, 0xfd, 0x32, 0x32, 0x1b, 0x7a, 0x38, 0x39, 0x8a, 0x55, 0x12, 0xef,
	0x04, 0xa0, 0x8d, 0x22, 0x54, 0x70, 0xd2, 0xdd, 0x8f, 0xca, 0x6b, 0x32, 0x83, 0xa1, 0x35, 0xd3,
	0x8d, 0x93, 0x63, 0x9d, 0xce, 0x36, 0x4e, 0xdd, 0x2c, 0x74, 0x5b, 0x6f, 0xe6, 0xfb, 0xc0, 0x42,
	0x73, 0x29, 0xda, 0x49, 0xd6, 0x70, 0x32, 0x87, 0xc1, 0xdc, 0x9e, 0xca, 0xac, 0xe1, 0x1e, 0xbc,
	0xdd, 0xf6, 0xc4, 0x36, 0xf9, 0xe7, 0x68, 0xe3, 0xd3, 0xbf, 0x1f, 0x55, 0x5e, 0x27, 0x7b, 0xf6,
	0xec, 0x97, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x22, 0xdd, 0xa2, 0x3f, 0x0a, 0x02, 0x00, 0x00,
}
