// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet_key/pkg/grpc/pb/wallet_key.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GenerateMnemonicRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateMnemonicRequest) Reset()         { *m = GenerateMnemonicRequest{} }
func (m *GenerateMnemonicRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateMnemonicRequest) ProtoMessage()    {}
func (*GenerateMnemonicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_key_dcc2a0f28280f464, []int{0}
}
func (m *GenerateMnemonicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateMnemonicRequest.Unmarshal(m, b)
}
func (m *GenerateMnemonicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateMnemonicRequest.Marshal(b, m, deterministic)
}
func (dst *GenerateMnemonicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateMnemonicRequest.Merge(dst, src)
}
func (m *GenerateMnemonicRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateMnemonicRequest.Size(m)
}
func (m *GenerateMnemonicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateMnemonicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateMnemonicRequest proto.InternalMessageInfo

func (m *GenerateMnemonicRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GenerateMnemonicRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GenerateMnemonicReply struct {
	Xpub                 string   `protobuf:"bytes,1,opt,name=xpub" json:"xpub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateMnemonicReply) Reset()         { *m = GenerateMnemonicReply{} }
func (m *GenerateMnemonicReply) String() string { return proto.CompactTextString(m) }
func (*GenerateMnemonicReply) ProtoMessage()    {}
func (*GenerateMnemonicReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_key_dcc2a0f28280f464, []int{1}
}
func (m *GenerateMnemonicReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateMnemonicReply.Unmarshal(m, b)
}
func (m *GenerateMnemonicReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateMnemonicReply.Marshal(b, m, deterministic)
}
func (dst *GenerateMnemonicReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateMnemonicReply.Merge(dst, src)
}
func (m *GenerateMnemonicReply) XXX_Size() int {
	return xxx_messageInfo_GenerateMnemonicReply.Size(m)
}
func (m *GenerateMnemonicReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateMnemonicReply.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateMnemonicReply proto.InternalMessageInfo

func (m *GenerateMnemonicReply) GetXpub() string {
	if m != nil {
		return m.Xpub
	}
	return ""
}

func init() {
	proto.RegisterType((*GenerateMnemonicRequest)(nil), "pb.GenerateMnemonicRequest")
	proto.RegisterType((*GenerateMnemonicReply)(nil), "pb.GenerateMnemonicReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletKeyClient is the client API for WalletKey service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletKeyClient interface {
	GenerateMnemonic(ctx context.Context, in *GenerateMnemonicRequest, opts ...grpc.CallOption) (*GenerateMnemonicReply, error)
}

type walletKeyClient struct {
	cc *grpc.ClientConn
}

func NewWalletKeyClient(cc *grpc.ClientConn) WalletKeyClient {
	return &walletKeyClient{cc}
}

func (c *walletKeyClient) GenerateMnemonic(ctx context.Context, in *GenerateMnemonicRequest, opts ...grpc.CallOption) (*GenerateMnemonicReply, error) {
	out := new(GenerateMnemonicReply)
	err := c.cc.Invoke(ctx, "/pb.WalletKey/GenerateMnemonic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletKeyServer is the server API for WalletKey service.
type WalletKeyServer interface {
	GenerateMnemonic(context.Context, *GenerateMnemonicRequest) (*GenerateMnemonicReply, error)
}

func RegisterWalletKeyServer(s *grpc.Server, srv WalletKeyServer) {
	s.RegisterService(&_WalletKey_serviceDesc, srv)
}

func _WalletKey_GenerateMnemonic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateMnemonicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletKeyServer).GenerateMnemonic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletKey/GenerateMnemonic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletKeyServer).GenerateMnemonic(ctx, req.(*GenerateMnemonicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletKey_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.WalletKey",
	HandlerType: (*WalletKeyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateMnemonic",
			Handler:    _WalletKey_GenerateMnemonic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet_key/pkg/grpc/pb/wallet_key.proto",
}

func init() {
	proto.RegisterFile("wallet_key/pkg/grpc/pb/wallet_key.proto", fileDescriptor_wallet_key_dcc2a0f28280f464)
}

var fileDescriptor_wallet_key_dcc2a0f28280f464 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2f, 0x4f, 0xcc, 0xc9,
	0x49, 0x2d, 0x89, 0xcf, 0x4e, 0xad, 0xd4, 0x2f, 0xc8, 0x4e, 0xd7, 0x4f, 0x2f, 0x2a, 0x48, 0xd6,
	0x2f, 0x48, 0xd2, 0x47, 0x08, 0xeb, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x31, 0x15, 0x24, 0x29,
	0x39, 0x73, 0x89, 0xbb, 0xa7, 0xe6, 0xa5, 0x16, 0x25, 0x96, 0xa4, 0xfa, 0xe6, 0xa5, 0xe6, 0xe6,
	0xe7, 0x65, 0x26, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x71, 0xb1, 0x94, 0x96,
	0x66, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0xa9,
	0xb9, 0x89, 0x99, 0x39, 0x12, 0x4c, 0x60, 0x41, 0x08, 0x47, 0x49, 0x9b, 0x4b, 0x14, 0xd3, 0x90,
	0x82, 0x9c, 0x4a, 0x90, 0x11, 0x15, 0x05, 0xa5, 0x49, 0x30, 0x23, 0x40, 0x6c, 0xa3, 0x70, 0x2e,
	0xce, 0x70, 0xb0, 0x4b, 0xbc, 0x53, 0x2b, 0x85, 0xbc, 0xb8, 0x04, 0xd0, 0x75, 0x0a, 0x49, 0xeb,
	0x15, 0x24, 0xe9, 0xe1, 0x70, 0x94, 0x94, 0x24, 0x76, 0xc9, 0x82, 0x9c, 0xca, 0x24, 0x36, 0xb0,
	0xaf, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xcc, 0x84, 0x22, 0x00, 0x01, 0x00, 0x00,
}
