// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dashboard.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetGroupsRequest struct {
	NamespaceID          string   `protobuf:"bytes,1,opt,name=namespaceID" json:"namespaceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupsRequest) Reset()         { *m = GetGroupsRequest{} }
func (m *GetGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupsRequest) ProtoMessage()    {}
func (*GetGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dashboard_23af37552b1c0d4f, []int{0}
}
func (m *GetGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupsRequest.Unmarshal(m, b)
}
func (m *GetGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupsRequest.Marshal(b, m, deterministic)
}
func (dst *GetGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupsRequest.Merge(dst, src)
}
func (m *GetGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupsRequest.Size(m)
}
func (m *GetGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupsRequest proto.InternalMessageInfo

func (m *GetGroupsRequest) GetNamespaceID() string {
	if m != nil {
		return m.NamespaceID
	}
	return ""
}

type GetGroupsReply struct {
	Groups               []*Group `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupsReply) Reset()         { *m = GetGroupsReply{} }
func (m *GetGroupsReply) String() string { return proto.CompactTextString(m) }
func (*GetGroupsReply) ProtoMessage()    {}
func (*GetGroupsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_dashboard_23af37552b1c0d4f, []int{1}
}
func (m *GetGroupsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupsReply.Unmarshal(m, b)
}
func (m *GetGroupsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupsReply.Marshal(b, m, deterministic)
}
func (dst *GetGroupsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupsReply.Merge(dst, src)
}
func (m *GetGroupsReply) XXX_Size() int {
	return xxx_messageInfo_GetGroupsReply.Size(m)
}
func (m *GetGroupsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupsReply proto.InternalMessageInfo

func (m *GetGroupsReply) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type Group struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc" json:"desc,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_dashboard_23af37552b1c0d4f, []int{2}
}
func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (dst *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(dst, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Group) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateGroupRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	NamespaceID          string   `protobuf:"bytes,4,opt,name=namespaceID" json:"namespaceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()    {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dashboard_23af37552b1c0d4f, []int{3}
}
func (m *CreateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRequest.Unmarshal(m, b)
}
func (m *CreateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRequest.Marshal(b, m, deterministic)
}
func (dst *CreateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRequest.Merge(dst, src)
}
func (m *CreateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRequest.Size(m)
}
func (m *CreateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRequest proto.InternalMessageInfo

func (m *CreateGroupRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CreateGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateGroupRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CreateGroupRequest) GetNamespaceID() string {
	if m != nil {
		return m.NamespaceID
	}
	return ""
}

type CreateGroupReply struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupReply) Reset()         { *m = CreateGroupReply{} }
func (m *CreateGroupReply) String() string { return proto.CompactTextString(m) }
func (*CreateGroupReply) ProtoMessage()    {}
func (*CreateGroupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_dashboard_23af37552b1c0d4f, []int{4}
}
func (m *CreateGroupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupReply.Unmarshal(m, b)
}
func (m *CreateGroupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupReply.Marshal(b, m, deterministic)
}
func (dst *CreateGroupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupReply.Merge(dst, src)
}
func (m *CreateGroupReply) XXX_Size() int {
	return xxx_messageInfo_CreateGroupReply.Size(m)
}
func (m *CreateGroupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupReply proto.InternalMessageInfo

func (m *CreateGroupReply) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type UpdateGroupRequest struct {
	Groupid              string   `protobuf:"bytes,1,opt,name=groupid" json:"groupid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupRequest) Reset()         { *m = UpdateGroupRequest{} }
func (m *UpdateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupRequest) ProtoMessage()    {}
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dashboard_23af37552b1c0d4f, []int{5}
}
func (m *UpdateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupRequest.Unmarshal(m, b)
}
func (m *UpdateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupRequest.Merge(dst, src)
}
func (m *UpdateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupRequest.Size(m)
}
func (m *UpdateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupRequest proto.InternalMessageInfo

func (m *UpdateGroupRequest) GetGroupid() string {
	if m != nil {
		return m.Groupid
	}
	return ""
}

func (m *UpdateGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateGroupRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type UpdateGroupReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupReply) Reset()         { *m = UpdateGroupReply{} }
func (m *UpdateGroupReply) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupReply) ProtoMessage()    {}
func (*UpdateGroupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_dashboard_23af37552b1c0d4f, []int{6}
}
func (m *UpdateGroupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupReply.Unmarshal(m, b)
}
func (m *UpdateGroupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupReply.Marshal(b, m, deterministic)
}
func (dst *UpdateGroupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupReply.Merge(dst, src)
}
func (m *UpdateGroupReply) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupReply.Size(m)
}
func (m *UpdateGroupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupReply proto.InternalMessageInfo

type GetGroupAssetRequest struct {
	Groupid              string   `protobuf:"bytes,1,opt,name=groupid" json:"groupid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupAssetRequest) Reset()         { *m = GetGroupAssetRequest{} }
func (m *GetGroupAssetRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupAssetRequest) ProtoMessage()    {}
func (*GetGroupAssetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dashboard_23af37552b1c0d4f, []int{7}
}
func (m *GetGroupAssetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupAssetRequest.Unmarshal(m, b)
}
func (m *GetGroupAssetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupAssetRequest.Marshal(b, m, deterministic)
}
func (dst *GetGroupAssetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupAssetRequest.Merge(dst, src)
}
func (m *GetGroupAssetRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupAssetRequest.Size(m)
}
func (m *GetGroupAssetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupAssetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupAssetRequest proto.InternalMessageInfo

func (m *GetGroupAssetRequest) GetGroupid() string {
	if m != nil {
		return m.Groupid
	}
	return ""
}

type SimpleAsset struct {
	AssetID              string   `protobuf:"bytes,1,opt,name=AssetID" json:"AssetID,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol" json:"symbol,omitempty"`
	Status               bool     `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleAsset) Reset()         { *m = SimpleAsset{} }
func (m *SimpleAsset) String() string { return proto.CompactTextString(m) }
func (*SimpleAsset) ProtoMessage()    {}
func (*SimpleAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_dashboard_23af37552b1c0d4f, []int{8}
}
func (m *SimpleAsset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleAsset.Unmarshal(m, b)
}
func (m *SimpleAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleAsset.Marshal(b, m, deterministic)
}
func (dst *SimpleAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleAsset.Merge(dst, src)
}
func (m *SimpleAsset) XXX_Size() int {
	return xxx_messageInfo_SimpleAsset.Size(m)
}
func (m *SimpleAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleAsset.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleAsset proto.InternalMessageInfo

func (m *SimpleAsset) GetAssetID() string {
	if m != nil {
		return m.AssetID
	}
	return ""
}

func (m *SimpleAsset) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *SimpleAsset) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type ChainAsset struct {
	ChainID              string         `protobuf:"bytes,1,opt,name=chainID" json:"chainID,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Coin                 string         `protobuf:"bytes,3,opt,name=coin" json:"coin,omitempty"`
	Status               bool           `protobuf:"varint,4,opt,name=status" json:"status,omitempty"`
	SimpleAssets         []*SimpleAsset `protobuf:"bytes,5,rep,name=SimpleAssets" json:"SimpleAssets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ChainAsset) Reset()         { *m = ChainAsset{} }
func (m *ChainAsset) String() string { return proto.CompactTextString(m) }
func (*ChainAsset) ProtoMessage()    {}
func (*ChainAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_dashboard_23af37552b1c0d4f, []int{9}
}
func (m *ChainAsset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainAsset.Unmarshal(m, b)
}
func (m *ChainAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainAsset.Marshal(b, m, deterministic)
}
func (dst *ChainAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainAsset.Merge(dst, src)
}
func (m *ChainAsset) XXX_Size() int {
	return xxx_messageInfo_ChainAsset.Size(m)
}
func (m *ChainAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainAsset.DiscardUnknown(m)
}

var xxx_messageInfo_ChainAsset proto.InternalMessageInfo

func (m *ChainAsset) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *ChainAsset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChainAsset) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *ChainAsset) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *ChainAsset) GetSimpleAssets() []*SimpleAsset {
	if m != nil {
		return m.SimpleAssets
	}
	return nil
}

type GetGroupAssetReply struct {
	Chainassets          []*ChainAsset `protobuf:"bytes,1,rep,name=chainassets" json:"chainassets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetGroupAssetReply) Reset()         { *m = GetGroupAssetReply{} }
func (m *GetGroupAssetReply) String() string { return proto.CompactTextString(m) }
func (*GetGroupAssetReply) ProtoMessage()    {}
func (*GetGroupAssetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_dashboard_23af37552b1c0d4f, []int{10}
}
func (m *GetGroupAssetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupAssetReply.Unmarshal(m, b)
}
func (m *GetGroupAssetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupAssetReply.Marshal(b, m, deterministic)
}
func (dst *GetGroupAssetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupAssetReply.Merge(dst, src)
}
func (m *GetGroupAssetReply) XXX_Size() int {
	return xxx_messageInfo_GetGroupAssetReply.Size(m)
}
func (m *GetGroupAssetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupAssetReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupAssetReply proto.InternalMessageInfo

func (m *GetGroupAssetReply) GetChainassets() []*ChainAsset {
	if m != nil {
		return m.Chainassets
	}
	return nil
}

type ChangeGroupAssetsRequest struct {
	Chainassets          []*ChainAsset `protobuf:"bytes,1,rep,name=chainassets" json:"chainassets,omitempty"`
	Groupid              string        `protobuf:"bytes,2,opt,name=groupid" json:"groupid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ChangeGroupAssetsRequest) Reset()         { *m = ChangeGroupAssetsRequest{} }
func (m *ChangeGroupAssetsRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeGroupAssetsRequest) ProtoMessage()    {}
func (*ChangeGroupAssetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dashboard_23af37552b1c0d4f, []int{11}
}
func (m *ChangeGroupAssetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeGroupAssetsRequest.Unmarshal(m, b)
}
func (m *ChangeGroupAssetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeGroupAssetsRequest.Marshal(b, m, deterministic)
}
func (dst *ChangeGroupAssetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeGroupAssetsRequest.Merge(dst, src)
}
func (m *ChangeGroupAssetsRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeGroupAssetsRequest.Size(m)
}
func (m *ChangeGroupAssetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeGroupAssetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeGroupAssetsRequest proto.InternalMessageInfo

func (m *ChangeGroupAssetsRequest) GetChainassets() []*ChainAsset {
	if m != nil {
		return m.Chainassets
	}
	return nil
}

func (m *ChangeGroupAssetsRequest) GetGroupid() string {
	if m != nil {
		return m.Groupid
	}
	return ""
}

type ChangeGroupAssetsReply struct {
	Chainassets          []*ChainAsset `protobuf:"bytes,1,rep,name=chainassets" json:"chainassets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ChangeGroupAssetsReply) Reset()         { *m = ChangeGroupAssetsReply{} }
func (m *ChangeGroupAssetsReply) String() string { return proto.CompactTextString(m) }
func (*ChangeGroupAssetsReply) ProtoMessage()    {}
func (*ChangeGroupAssetsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_dashboard_23af37552b1c0d4f, []int{12}
}
func (m *ChangeGroupAssetsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeGroupAssetsReply.Unmarshal(m, b)
}
func (m *ChangeGroupAssetsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeGroupAssetsReply.Marshal(b, m, deterministic)
}
func (dst *ChangeGroupAssetsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeGroupAssetsReply.Merge(dst, src)
}
func (m *ChangeGroupAssetsReply) XXX_Size() int {
	return xxx_messageInfo_ChangeGroupAssetsReply.Size(m)
}
func (m *ChangeGroupAssetsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeGroupAssetsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeGroupAssetsReply proto.InternalMessageInfo

func (m *ChangeGroupAssetsReply) GetChainassets() []*ChainAsset {
	if m != nil {
		return m.Chainassets
	}
	return nil
}

func init() {
	proto.RegisterType((*GetGroupsRequest)(nil), "pb.GetGroupsRequest")
	proto.RegisterType((*GetGroupsReply)(nil), "pb.GetGroupsReply")
	proto.RegisterType((*Group)(nil), "pb.Group")
	proto.RegisterType((*CreateGroupRequest)(nil), "pb.CreateGroupRequest")
	proto.RegisterType((*CreateGroupReply)(nil), "pb.CreateGroupReply")
	proto.RegisterType((*UpdateGroupRequest)(nil), "pb.UpdateGroupRequest")
	proto.RegisterType((*UpdateGroupReply)(nil), "pb.UpdateGroupReply")
	proto.RegisterType((*GetGroupAssetRequest)(nil), "pb.GetGroupAssetRequest")
	proto.RegisterType((*SimpleAsset)(nil), "pb.SimpleAsset")
	proto.RegisterType((*ChainAsset)(nil), "pb.ChainAsset")
	proto.RegisterType((*GetGroupAssetReply)(nil), "pb.GetGroupAssetReply")
	proto.RegisterType((*ChangeGroupAssetsRequest)(nil), "pb.ChangeGroupAssetsRequest")
	proto.RegisterType((*ChangeGroupAssetsReply)(nil), "pb.ChangeGroupAssetsReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DashboardClient is the client API for Dashboard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DashboardClient interface {
	GetGroups(ctx context.Context, in *GetGroupsRequest, opts ...grpc.CallOption) (*GetGroupsReply, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupReply, error)
	UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupReply, error)
	GetGroupAsset(ctx context.Context, in *GetGroupAssetRequest, opts ...grpc.CallOption) (*GetGroupAssetReply, error)
	ChangeGroupAssets(ctx context.Context, in *ChangeGroupAssetsRequest, opts ...grpc.CallOption) (*ChangeGroupAssetsReply, error)
}

type dashboardClient struct {
	cc *grpc.ClientConn
}

func NewDashboardClient(cc *grpc.ClientConn) DashboardClient {
	return &dashboardClient{cc}
}

func (c *dashboardClient) GetGroups(ctx context.Context, in *GetGroupsRequest, opts ...grpc.CallOption) (*GetGroupsReply, error) {
	out := new(GetGroupsReply)
	err := c.cc.Invoke(ctx, "/pb.Dashboard/GetGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupReply, error) {
	out := new(CreateGroupReply)
	err := c.cc.Invoke(ctx, "/pb.Dashboard/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupReply, error) {
	out := new(UpdateGroupReply)
	err := c.cc.Invoke(ctx, "/pb.Dashboard/UpdateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) GetGroupAsset(ctx context.Context, in *GetGroupAssetRequest, opts ...grpc.CallOption) (*GetGroupAssetReply, error) {
	out := new(GetGroupAssetReply)
	err := c.cc.Invoke(ctx, "/pb.Dashboard/GetGroupAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) ChangeGroupAssets(ctx context.Context, in *ChangeGroupAssetsRequest, opts ...grpc.CallOption) (*ChangeGroupAssetsReply, error) {
	out := new(ChangeGroupAssetsReply)
	err := c.cc.Invoke(ctx, "/pb.Dashboard/ChangeGroupAssets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashboardServer is the server API for Dashboard service.
type DashboardServer interface {
	GetGroups(context.Context, *GetGroupsRequest) (*GetGroupsReply, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupReply, error)
	UpdateGroup(context.Context, *UpdateGroupRequest) (*UpdateGroupReply, error)
	GetGroupAsset(context.Context, *GetGroupAssetRequest) (*GetGroupAssetReply, error)
	ChangeGroupAssets(context.Context, *ChangeGroupAssetsRequest) (*ChangeGroupAssetsReply, error)
}

func RegisterDashboardServer(s *grpc.Server, srv DashboardServer) {
	s.RegisterService(&_Dashboard_serviceDesc, srv)
}

func _Dashboard_GetGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).GetGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Dashboard/GetGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).GetGroups(ctx, req.(*GetGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Dashboard/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Dashboard/UpdateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).UpdateGroup(ctx, req.(*UpdateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_GetGroupAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).GetGroupAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Dashboard/GetGroupAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).GetGroupAsset(ctx, req.(*GetGroupAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_ChangeGroupAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeGroupAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).ChangeGroupAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Dashboard/ChangeGroupAssets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).ChangeGroupAssets(ctx, req.(*ChangeGroupAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dashboard_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Dashboard",
	HandlerType: (*DashboardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGroups",
			Handler:    _Dashboard_GetGroups_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _Dashboard_CreateGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _Dashboard_UpdateGroup_Handler,
		},
		{
			MethodName: "GetGroupAsset",
			Handler:    _Dashboard_GetGroupAsset_Handler,
		},
		{
			MethodName: "ChangeGroupAssets",
			Handler:    _Dashboard_ChangeGroupAssets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dashboard.proto",
}

func init() { proto.RegisterFile("dashboard.proto", fileDescriptor_dashboard_23af37552b1c0d4f) }

var fileDescriptor_dashboard_23af37552b1c0d4f = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x56, 0xd3, 0x1f, 0xe8, 0x04, 0xba, 0x65, 0x54, 0x55, 0x51, 0x84, 0x44, 0xf1, 0x69, 0x4f,
	0xd5, 0x6a, 0x0b, 0x27, 0x0e, 0x68, 0xd5, 0x15, 0x2b, 0x90, 0xb8, 0x04, 0x01, 0x67, 0xa7, 0x31,
	0xdb, 0x48, 0x69, 0x63, 0xe2, 0xe4, 0xd0, 0x67, 0xe1, 0x9d, 0x78, 0x26, 0xe4, 0x89, 0x93, 0x3a,
	0x3f, 0x2b, 0x60, 0x6f, 0x33, 0x9f, 0xc7, 0xdf, 0x37, 0xe3, 0x99, 0x31, 0x5c, 0x44, 0x5c, 0xed,
	0xc3, 0x94, 0x67, 0xd1, 0x5a, 0x66, 0x69, 0x9e, 0xa2, 0x23, 0x43, 0xf6, 0x06, 0xe6, 0x77, 0x22,
	0xbf, 0xcb, 0xd2, 0x42, 0xaa, 0x40, 0xfc, 0x2c, 0x84, 0xca, 0x71, 0x05, 0xee, 0x91, 0x1f, 0x84,
	0x92, 0x7c, 0x27, 0x3e, 0xde, 0x7a, 0x83, 0xd5, 0xe0, 0x72, 0x1a, 0xd8, 0x10, 0xdb, 0xc0, 0xcc,
	0xba, 0x25, 0x93, 0x13, 0xbe, 0x86, 0xc9, 0x3d, 0xb9, 0xde, 0x60, 0x35, 0xbc, 0x74, 0xaf, 0xa7,
	0x6b, 0x19, 0xae, 0x29, 0x20, 0x30, 0x07, 0xec, 0x3d, 0x8c, 0x09, 0x40, 0x84, 0x91, 0x26, 0x33,
	0xc4, 0x64, 0x6b, 0x2c, 0x12, 0x6a, 0xe7, 0x39, 0x25, 0xa6, 0x6d, 0x9c, 0x81, 0x13, 0x47, 0xde,
	0x90, 0x10, 0x27, 0x8e, 0x58, 0x06, 0xb8, 0xcd, 0x04, 0xcf, 0x45, 0xc9, 0x6b, 0xb2, 0x45, 0x18,
	0x15, 0x45, 0x1c, 0x55, 0x6c, 0xda, 0xae, 0x15, 0x9c, 0x1e, 0x85, 0xa1, 0xa5, 0xd0, 0xaa, 0x74,
	0xd4, 0x57, 0xe9, 0xbc, 0xa1, 0xa9, 0x6b, 0x7d, 0x05, 0x63, 0x2a, 0x89, 0x24, 0x1b, 0xa5, 0x96,
	0x38, 0xfb, 0x06, 0xf8, 0x55, 0x46, 0xed, 0x44, 0x3d, 0x78, 0x42, 0xc7, 0x75, 0xae, 0x95, 0xfb,
	0xaf, 0xe9, 0x32, 0x84, 0x79, 0x83, 0x57, 0x26, 0x27, 0x76, 0x05, 0x8b, 0xaa, 0x15, 0x37, 0x4a,
	0x89, 0xfc, 0xaf, 0x6a, 0xec, 0x3b, 0xb8, 0x5f, 0xe2, 0x83, 0x4c, 0x04, 0xc5, 0xeb, 0x40, 0x32,
	0xea, 0x4e, 0x57, 0x2e, 0x2e, 0x61, 0xa2, 0x4e, 0x87, 0x30, 0x4d, 0x4c, 0x62, 0xc6, 0x23, 0x3c,
	0xe7, 0x79, 0xa1, 0x28, 0xb9, 0xa7, 0x81, 0xf1, 0xd8, 0xaf, 0x01, 0xc0, 0x76, 0xcf, 0xe3, 0x63,
	0x4d, 0xbc, 0xd3, 0xde, 0x99, 0xd8, 0xb8, 0x0f, 0xd5, 0xbb, 0x4b, 0xe3, 0x63, 0x55, 0xaf, 0xb6,
	0x2d, 0xa1, 0x91, 0x2d, 0x84, 0x1b, 0x78, 0x66, 0x55, 0xa0, 0xbc, 0x31, 0x8d, 0xdc, 0x85, 0xee,
	0x83, 0x85, 0x07, 0x8d, 0x20, 0xf6, 0x01, 0xb0, 0xf5, 0x50, 0xba, 0x97, 0x57, 0xe0, 0x52, 0x56,
	0xbc, 0x64, 0x2a, 0x87, 0x77, 0xa6, 0x99, 0xce, 0x95, 0x04, 0x76, 0x08, 0xfb, 0x01, 0xde, 0x76,
	0xcf, 0x8f, 0xf7, 0xe2, 0x4c, 0x55, 0x6f, 0xce, 0x7f, 0xb3, 0xd9, 0x6d, 0x72, 0x9a, 0x6d, 0xfa,
	0x04, 0xcb, 0x1e, 0x9d, 0x47, 0xe5, 0x7c, 0xfd, 0xdb, 0x81, 0xe9, 0x6d, 0xb5, 0xfd, 0xf8, 0x16,
	0xa6, 0xf5, 0xf6, 0xe2, 0x82, 0xa6, 0xb7, 0xf5, 0x05, 0xf8, 0xd8, 0x42, 0xb5, 0xec, 0x3b, 0x70,
	0xad, 0x55, 0xc0, 0x25, 0x09, 0x76, 0xf6, 0xd1, 0x5f, 0x74, 0x70, 0x73, 0xd9, 0x1a, 0xdd, 0xf2,
	0x72, 0x77, 0x47, 0xca, 0xcb, 0xed, 0x19, 0xc7, 0x1b, 0x78, 0xde, 0x68, 0x1d, 0x7a, 0x76, 0x7a,
	0xf6, 0xd8, 0xfb, 0xcb, 0x9e, 0x13, 0x4d, 0xf1, 0x19, 0x5e, 0x74, 0x5e, 0x13, 0x5f, 0x9a, 0x37,
	0xeb, 0x6d, 0xa6, 0xef, 0x3f, 0x70, 0x2a, 0x93, 0x53, 0x38, 0xa1, 0x1f, 0x74, 0xf3, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x90, 0x61, 0xd2, 0x71, 0x54, 0x05, 0x00, 0x00,
}
