// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chains_query.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BitcoincoreBlockRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BitcoincoreBlockRequest) Reset()         { *m = BitcoincoreBlockRequest{} }
func (m *BitcoincoreBlockRequest) String() string { return proto.CompactTextString(m) }
func (*BitcoincoreBlockRequest) ProtoMessage()    {}
func (*BitcoincoreBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{0}
}
func (m *BitcoincoreBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitcoincoreBlockRequest.Unmarshal(m, b)
}
func (m *BitcoincoreBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitcoincoreBlockRequest.Marshal(b, m, deterministic)
}
func (dst *BitcoincoreBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitcoincoreBlockRequest.Merge(dst, src)
}
func (m *BitcoincoreBlockRequest) XXX_Size() int {
	return xxx_messageInfo_BitcoincoreBlockRequest.Size(m)
}
func (m *BitcoincoreBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BitcoincoreBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BitcoincoreBlockRequest proto.InternalMessageInfo

type BitcoincoreBlockReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BitcoincoreBlockReply) Reset()         { *m = BitcoincoreBlockReply{} }
func (m *BitcoincoreBlockReply) String() string { return proto.CompactTextString(m) }
func (*BitcoincoreBlockReply) ProtoMessage()    {}
func (*BitcoincoreBlockReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{1}
}
func (m *BitcoincoreBlockReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitcoincoreBlockReply.Unmarshal(m, b)
}
func (m *BitcoincoreBlockReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitcoincoreBlockReply.Marshal(b, m, deterministic)
}
func (dst *BitcoincoreBlockReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitcoincoreBlockReply.Merge(dst, src)
}
func (m *BitcoincoreBlockReply) XXX_Size() int {
	return xxx_messageInfo_BitcoincoreBlockReply.Size(m)
}
func (m *BitcoincoreBlockReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BitcoincoreBlockReply.DiscardUnknown(m)
}

var xxx_messageInfo_BitcoincoreBlockReply proto.InternalMessageInfo

type QueryOmniPropertyRequest struct {
	Propertyid           int64    `protobuf:"varint,1,opt,name=propertyid" json:"propertyid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOmniPropertyRequest) Reset()         { *m = QueryOmniPropertyRequest{} }
func (m *QueryOmniPropertyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOmniPropertyRequest) ProtoMessage()    {}
func (*QueryOmniPropertyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{2}
}
func (m *QueryOmniPropertyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOmniPropertyRequest.Unmarshal(m, b)
}
func (m *QueryOmniPropertyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOmniPropertyRequest.Marshal(b, m, deterministic)
}
func (dst *QueryOmniPropertyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOmniPropertyRequest.Merge(dst, src)
}
func (m *QueryOmniPropertyRequest) XXX_Size() int {
	return xxx_messageInfo_QueryOmniPropertyRequest.Size(m)
}
func (m *QueryOmniPropertyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOmniPropertyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOmniPropertyRequest proto.InternalMessageInfo

func (m *QueryOmniPropertyRequest) GetPropertyid() int64 {
	if m != nil {
		return m.Propertyid
	}
	return 0
}

type OmniProperty struct {
	Propertyid           int64    `protobuf:"varint,1,opt,name=Propertyid" json:"Propertyid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=Category" json:"Category,omitempty"`
	Subcategory          string   `protobuf:"bytes,4,opt,name=Subcategory" json:"Subcategory,omitempty"`
	URL                  string   `protobuf:"bytes,5,opt,name=URL" json:"URL,omitempty"`
	Divisible            bool     `protobuf:"varint,6,opt,name=Divisible" json:"Divisible,omitempty"`
	Issuer               string   `protobuf:"bytes,7,opt,name=Issuer" json:"Issuer,omitempty"`
	Creationtxid         string   `protobuf:"bytes,8,opt,name=Creationtxid" json:"Creationtxid,omitempty"`
	Fixedissuance        bool     `protobuf:"varint,9,opt,name=Fixedissuance" json:"Fixedissuance,omitempty"`
	Managedissuance      bool     `protobuf:"varint,10,opt,name=Managedissuance" json:"Managedissuance,omitempty"`
	Freezingenabled      bool     `protobuf:"varint,11,opt,name=Freezingenabled" json:"Freezingenabled,omitempty"`
	Totaltokens          string   `protobuf:"bytes,12,opt,name=Totaltokens" json:"Totaltokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OmniProperty) Reset()         { *m = OmniProperty{} }
func (m *OmniProperty) String() string { return proto.CompactTextString(m) }
func (*OmniProperty) ProtoMessage()    {}
func (*OmniProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{3}
}
func (m *OmniProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OmniProperty.Unmarshal(m, b)
}
func (m *OmniProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OmniProperty.Marshal(b, m, deterministic)
}
func (dst *OmniProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OmniProperty.Merge(dst, src)
}
func (m *OmniProperty) XXX_Size() int {
	return xxx_messageInfo_OmniProperty.Size(m)
}
func (m *OmniProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_OmniProperty.DiscardUnknown(m)
}

var xxx_messageInfo_OmniProperty proto.InternalMessageInfo

func (m *OmniProperty) GetPropertyid() int64 {
	if m != nil {
		return m.Propertyid
	}
	return 0
}

func (m *OmniProperty) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OmniProperty) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *OmniProperty) GetSubcategory() string {
	if m != nil {
		return m.Subcategory
	}
	return ""
}

func (m *OmniProperty) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *OmniProperty) GetDivisible() bool {
	if m != nil {
		return m.Divisible
	}
	return false
}

func (m *OmniProperty) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *OmniProperty) GetCreationtxid() string {
	if m != nil {
		return m.Creationtxid
	}
	return ""
}

func (m *OmniProperty) GetFixedissuance() bool {
	if m != nil {
		return m.Fixedissuance
	}
	return false
}

func (m *OmniProperty) GetManagedissuance() bool {
	if m != nil {
		return m.Managedissuance
	}
	return false
}

func (m *OmniProperty) GetFreezingenabled() bool {
	if m != nil {
		return m.Freezingenabled
	}
	return false
}

func (m *OmniProperty) GetTotaltokens() string {
	if m != nil {
		return m.Totaltokens
	}
	return ""
}

type QueryOmniPropertyReply struct {
	OmniProperty         *OmniProperty `protobuf:"bytes,1,opt,name=OmniProperty" json:"OmniProperty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QueryOmniPropertyReply) Reset()         { *m = QueryOmniPropertyReply{} }
func (m *QueryOmniPropertyReply) String() string { return proto.CompactTextString(m) }
func (*QueryOmniPropertyReply) ProtoMessage()    {}
func (*QueryOmniPropertyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{4}
}
func (m *QueryOmniPropertyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOmniPropertyReply.Unmarshal(m, b)
}
func (m *QueryOmniPropertyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOmniPropertyReply.Marshal(b, m, deterministic)
}
func (dst *QueryOmniPropertyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOmniPropertyReply.Merge(dst, src)
}
func (m *QueryOmniPropertyReply) XXX_Size() int {
	return xxx_messageInfo_QueryOmniPropertyReply.Size(m)
}
func (m *QueryOmniPropertyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOmniPropertyReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOmniPropertyReply proto.InternalMessageInfo

func (m *QueryOmniPropertyReply) GetOmniProperty() *OmniProperty {
	if m != nil {
		return m.OmniProperty
	}
	return nil
}

type ERC20TokenInfoRequest struct {
	TokenHex             string   `protobuf:"bytes,1,opt,name=TokenHex" json:"TokenHex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ERC20TokenInfoRequest) Reset()         { *m = ERC20TokenInfoRequest{} }
func (m *ERC20TokenInfoRequest) String() string { return proto.CompactTextString(m) }
func (*ERC20TokenInfoRequest) ProtoMessage()    {}
func (*ERC20TokenInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{5}
}
func (m *ERC20TokenInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ERC20TokenInfoRequest.Unmarshal(m, b)
}
func (m *ERC20TokenInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ERC20TokenInfoRequest.Marshal(b, m, deterministic)
}
func (dst *ERC20TokenInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ERC20TokenInfoRequest.Merge(dst, src)
}
func (m *ERC20TokenInfoRequest) XXX_Size() int {
	return xxx_messageInfo_ERC20TokenInfoRequest.Size(m)
}
func (m *ERC20TokenInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ERC20TokenInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ERC20TokenInfoRequest proto.InternalMessageInfo

func (m *ERC20TokenInfoRequest) GetTokenHex() string {
	if m != nil {
		return m.TokenHex
	}
	return ""
}

type ERC20Token struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=Symbol" json:"Symbol,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Decimals             uint64   `protobuf:"varint,3,opt,name=Decimals" json:"Decimals,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=Address" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ERC20Token) Reset()         { *m = ERC20Token{} }
func (m *ERC20Token) String() string { return proto.CompactTextString(m) }
func (*ERC20Token) ProtoMessage()    {}
func (*ERC20Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{6}
}
func (m *ERC20Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ERC20Token.Unmarshal(m, b)
}
func (m *ERC20Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ERC20Token.Marshal(b, m, deterministic)
}
func (dst *ERC20Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ERC20Token.Merge(dst, src)
}
func (m *ERC20Token) XXX_Size() int {
	return xxx_messageInfo_ERC20Token.Size(m)
}
func (m *ERC20Token) XXX_DiscardUnknown() {
	xxx_messageInfo_ERC20Token.DiscardUnknown(m)
}

var xxx_messageInfo_ERC20Token proto.InternalMessageInfo

func (m *ERC20Token) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ERC20Token) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ERC20Token) GetDecimals() uint64 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *ERC20Token) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ERC20TokenInfoReply struct {
	ERC20Token           *ERC20Token `protobuf:"bytes,1,opt,name=ERC20Token" json:"ERC20Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ERC20TokenInfoReply) Reset()         { *m = ERC20TokenInfoReply{} }
func (m *ERC20TokenInfoReply) String() string { return proto.CompactTextString(m) }
func (*ERC20TokenInfoReply) ProtoMessage()    {}
func (*ERC20TokenInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{7}
}
func (m *ERC20TokenInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ERC20TokenInfoReply.Unmarshal(m, b)
}
func (m *ERC20TokenInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ERC20TokenInfoReply.Marshal(b, m, deterministic)
}
func (dst *ERC20TokenInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ERC20TokenInfoReply.Merge(dst, src)
}
func (m *ERC20TokenInfoReply) XXX_Size() int {
	return xxx_messageInfo_ERC20TokenInfoReply.Size(m)
}
func (m *ERC20TokenInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ERC20TokenInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_ERC20TokenInfoReply proto.InternalMessageInfo

func (m *ERC20TokenInfoReply) GetERC20Token() *ERC20Token {
	if m != nil {
		return m.ERC20Token
	}
	return nil
}

type ConstructTxBTCRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=From" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=To" json:"To,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=Amount" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConstructTxBTCRequest) Reset()         { *m = ConstructTxBTCRequest{} }
func (m *ConstructTxBTCRequest) String() string { return proto.CompactTextString(m) }
func (*ConstructTxBTCRequest) ProtoMessage()    {}
func (*ConstructTxBTCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{8}
}
func (m *ConstructTxBTCRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConstructTxBTCRequest.Unmarshal(m, b)
}
func (m *ConstructTxBTCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConstructTxBTCRequest.Marshal(b, m, deterministic)
}
func (dst *ConstructTxBTCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConstructTxBTCRequest.Merge(dst, src)
}
func (m *ConstructTxBTCRequest) XXX_Size() int {
	return xxx_messageInfo_ConstructTxBTCRequest.Size(m)
}
func (m *ConstructTxBTCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConstructTxBTCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConstructTxBTCRequest proto.InternalMessageInfo

func (m *ConstructTxBTCRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ConstructTxBTCRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ConstructTxBTCRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type ConstructTxBTCReply struct {
	UnsignedTxHex        string   `protobuf:"bytes,1,opt,name=UnsignedTxHex" json:"UnsignedTxHex,omitempty"`
	VinAmount            int64    `protobuf:"varint,2,opt,name=VinAmount" json:"VinAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConstructTxBTCReply) Reset()         { *m = ConstructTxBTCReply{} }
func (m *ConstructTxBTCReply) String() string { return proto.CompactTextString(m) }
func (*ConstructTxBTCReply) ProtoMessage()    {}
func (*ConstructTxBTCReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{9}
}
func (m *ConstructTxBTCReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConstructTxBTCReply.Unmarshal(m, b)
}
func (m *ConstructTxBTCReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConstructTxBTCReply.Marshal(b, m, deterministic)
}
func (dst *ConstructTxBTCReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConstructTxBTCReply.Merge(dst, src)
}
func (m *ConstructTxBTCReply) XXX_Size() int {
	return xxx_messageInfo_ConstructTxBTCReply.Size(m)
}
func (m *ConstructTxBTCReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConstructTxBTCReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConstructTxBTCReply proto.InternalMessageInfo

func (m *ConstructTxBTCReply) GetUnsignedTxHex() string {
	if m != nil {
		return m.UnsignedTxHex
	}
	return ""
}

func (m *ConstructTxBTCReply) GetVinAmount() int64 {
	if m != nil {
		return m.VinAmount
	}
	return 0
}

type SendBTCTxRequest struct {
	SignedTxHex          string   `protobuf:"bytes,1,opt,name=SignedTxHex" json:"SignedTxHex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendBTCTxRequest) Reset()         { *m = SendBTCTxRequest{} }
func (m *SendBTCTxRequest) String() string { return proto.CompactTextString(m) }
func (*SendBTCTxRequest) ProtoMessage()    {}
func (*SendBTCTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{10}
}
func (m *SendBTCTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendBTCTxRequest.Unmarshal(m, b)
}
func (m *SendBTCTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendBTCTxRequest.Marshal(b, m, deterministic)
}
func (dst *SendBTCTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendBTCTxRequest.Merge(dst, src)
}
func (m *SendBTCTxRequest) XXX_Size() int {
	return xxx_messageInfo_SendBTCTxRequest.Size(m)
}
func (m *SendBTCTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendBTCTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendBTCTxRequest proto.InternalMessageInfo

func (m *SendBTCTxRequest) GetSignedTxHex() string {
	if m != nil {
		return m.SignedTxHex
	}
	return ""
}

type SendBTCTxReply struct {
	TxID                 string   `protobuf:"bytes,1,opt,name=TxID" json:"TxID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendBTCTxReply) Reset()         { *m = SendBTCTxReply{} }
func (m *SendBTCTxReply) String() string { return proto.CompactTextString(m) }
func (*SendBTCTxReply) ProtoMessage()    {}
func (*SendBTCTxReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{11}
}
func (m *SendBTCTxReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendBTCTxReply.Unmarshal(m, b)
}
func (m *SendBTCTxReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendBTCTxReply.Marshal(b, m, deterministic)
}
func (dst *SendBTCTxReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendBTCTxReply.Merge(dst, src)
}
func (m *SendBTCTxReply) XXX_Size() int {
	return xxx_messageInfo_SendBTCTxReply.Size(m)
}
func (m *SendBTCTxReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendBTCTxReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendBTCTxReply proto.InternalMessageInfo

func (m *SendBTCTxReply) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

type QueryBalanceRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBalanceRequest) Reset()         { *m = QueryBalanceRequest{} }
func (m *QueryBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBalanceRequest) ProtoMessage()    {}
func (*QueryBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{12}
}
func (m *QueryBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBalanceRequest.Unmarshal(m, b)
}
func (m *QueryBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBalanceRequest.Marshal(b, m, deterministic)
}
func (dst *QueryBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBalanceRequest.Merge(dst, src)
}
func (m *QueryBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_QueryBalanceRequest.Size(m)
}
func (m *QueryBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBalanceRequest proto.InternalMessageInfo

func (m *QueryBalanceRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *QueryBalanceRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryBalanceReply struct {
	Balance              string   `protobuf:"bytes,1,opt,name=balance" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBalanceReply) Reset()         { *m = QueryBalanceReply{} }
func (m *QueryBalanceReply) String() string { return proto.CompactTextString(m) }
func (*QueryBalanceReply) ProtoMessage()    {}
func (*QueryBalanceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{13}
}
func (m *QueryBalanceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBalanceReply.Unmarshal(m, b)
}
func (m *QueryBalanceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBalanceReply.Marshal(b, m, deterministic)
}
func (dst *QueryBalanceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBalanceReply.Merge(dst, src)
}
func (m *QueryBalanceReply) XXX_Size() int {
	return xxx_messageInfo_QueryBalanceReply.Size(m)
}
func (m *QueryBalanceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBalanceReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBalanceReply proto.InternalMessageInfo

func (m *QueryBalanceReply) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

type WalletValidateRequest struct {
	ChainName            string   `protobuf:"bytes,1,opt,name=chainName" json:"chainName,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletValidateRequest) Reset()         { *m = WalletValidateRequest{} }
func (m *WalletValidateRequest) String() string { return proto.CompactTextString(m) }
func (*WalletValidateRequest) ProtoMessage()    {}
func (*WalletValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{14}
}
func (m *WalletValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletValidateRequest.Unmarshal(m, b)
}
func (m *WalletValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletValidateRequest.Marshal(b, m, deterministic)
}
func (dst *WalletValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletValidateRequest.Merge(dst, src)
}
func (m *WalletValidateRequest) XXX_Size() int {
	return xxx_messageInfo_WalletValidateRequest.Size(m)
}
func (m *WalletValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WalletValidateRequest proto.InternalMessageInfo

func (m *WalletValidateRequest) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

func (m *WalletValidateRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type WalletValidateReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletValidateReply) Reset()         { *m = WalletValidateReply{} }
func (m *WalletValidateReply) String() string { return proto.CompactTextString(m) }
func (*WalletValidateReply) ProtoMessage()    {}
func (*WalletValidateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{15}
}
func (m *WalletValidateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletValidateReply.Unmarshal(m, b)
}
func (m *WalletValidateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletValidateReply.Marshal(b, m, deterministic)
}
func (dst *WalletValidateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletValidateReply.Merge(dst, src)
}
func (m *WalletValidateReply) XXX_Size() int {
	return xxx_messageInfo_WalletValidateReply.Size(m)
}
func (m *WalletValidateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletValidateReply.DiscardUnknown(m)
}

var xxx_messageInfo_WalletValidateReply proto.InternalMessageInfo

type ConstructTxETHRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=From" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=To" json:"To,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=Amount" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConstructTxETHRequest) Reset()         { *m = ConstructTxETHRequest{} }
func (m *ConstructTxETHRequest) String() string { return proto.CompactTextString(m) }
func (*ConstructTxETHRequest) ProtoMessage()    {}
func (*ConstructTxETHRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{16}
}
func (m *ConstructTxETHRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConstructTxETHRequest.Unmarshal(m, b)
}
func (m *ConstructTxETHRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConstructTxETHRequest.Marshal(b, m, deterministic)
}
func (dst *ConstructTxETHRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConstructTxETHRequest.Merge(dst, src)
}
func (m *ConstructTxETHRequest) XXX_Size() int {
	return xxx_messageInfo_ConstructTxETHRequest.Size(m)
}
func (m *ConstructTxETHRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConstructTxETHRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConstructTxETHRequest proto.InternalMessageInfo

func (m *ConstructTxETHRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ConstructTxETHRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ConstructTxETHRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type ConstructTxETHReply struct {
	UnsignedTxHex        string   `protobuf:"bytes,1,opt,name=UnsignedTxHex" json:"UnsignedTxHex,omitempty"`
	ChainID              string   `protobuf:"bytes,2,opt,name=ChainID" json:"ChainID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConstructTxETHReply) Reset()         { *m = ConstructTxETHReply{} }
func (m *ConstructTxETHReply) String() string { return proto.CompactTextString(m) }
func (*ConstructTxETHReply) ProtoMessage()    {}
func (*ConstructTxETHReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{17}
}
func (m *ConstructTxETHReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConstructTxETHReply.Unmarshal(m, b)
}
func (m *ConstructTxETHReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConstructTxETHReply.Marshal(b, m, deterministic)
}
func (dst *ConstructTxETHReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConstructTxETHReply.Merge(dst, src)
}
func (m *ConstructTxETHReply) XXX_Size() int {
	return xxx_messageInfo_ConstructTxETHReply.Size(m)
}
func (m *ConstructTxETHReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConstructTxETHReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConstructTxETHReply proto.InternalMessageInfo

func (m *ConstructTxETHReply) GetUnsignedTxHex() string {
	if m != nil {
		return m.UnsignedTxHex
	}
	return ""
}

func (m *ConstructTxETHReply) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

type SendETHTxRequest struct {
	SignedTxHex          string   `protobuf:"bytes,1,opt,name=SignedTxHex" json:"SignedTxHex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendETHTxRequest) Reset()         { *m = SendETHTxRequest{} }
func (m *SendETHTxRequest) String() string { return proto.CompactTextString(m) }
func (*SendETHTxRequest) ProtoMessage()    {}
func (*SendETHTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{18}
}
func (m *SendETHTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendETHTxRequest.Unmarshal(m, b)
}
func (m *SendETHTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendETHTxRequest.Marshal(b, m, deterministic)
}
func (dst *SendETHTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendETHTxRequest.Merge(dst, src)
}
func (m *SendETHTxRequest) XXX_Size() int {
	return xxx_messageInfo_SendETHTxRequest.Size(m)
}
func (m *SendETHTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendETHTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendETHTxRequest proto.InternalMessageInfo

func (m *SendETHTxRequest) GetSignedTxHex() string {
	if m != nil {
		return m.SignedTxHex
	}
	return ""
}

type SendETHTxReply struct {
	TxID                 string   `protobuf:"bytes,1,opt,name=TxID" json:"TxID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendETHTxReply) Reset()         { *m = SendETHTxReply{} }
func (m *SendETHTxReply) String() string { return proto.CompactTextString(m) }
func (*SendETHTxReply) ProtoMessage()    {}
func (*SendETHTxReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{19}
}
func (m *SendETHTxReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendETHTxReply.Unmarshal(m, b)
}
func (m *SendETHTxReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendETHTxReply.Marshal(b, m, deterministic)
}
func (dst *SendETHTxReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendETHTxReply.Merge(dst, src)
}
func (m *SendETHTxReply) XXX_Size() int {
	return xxx_messageInfo_SendETHTxReply.Size(m)
}
func (m *SendETHTxReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendETHTxReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendETHTxReply proto.InternalMessageInfo

func (m *SendETHTxReply) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

// ConstructTxERC20(ctx context.Context, from, to, amount, contract string) (unsignedTxHex, chainID string, err error)
type ConstructTxERC20Request struct {
	From                 string   `protobuf:"bytes,1,opt,name=From" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=To" json:"To,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=Amount" json:"Amount,omitempty"`
	Contract             string   `protobuf:"bytes,4,opt,name=Contract" json:"Contract,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConstructTxERC20Request) Reset()         { *m = ConstructTxERC20Request{} }
func (m *ConstructTxERC20Request) String() string { return proto.CompactTextString(m) }
func (*ConstructTxERC20Request) ProtoMessage()    {}
func (*ConstructTxERC20Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{20}
}
func (m *ConstructTxERC20Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConstructTxERC20Request.Unmarshal(m, b)
}
func (m *ConstructTxERC20Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConstructTxERC20Request.Marshal(b, m, deterministic)
}
func (dst *ConstructTxERC20Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConstructTxERC20Request.Merge(dst, src)
}
func (m *ConstructTxERC20Request) XXX_Size() int {
	return xxx_messageInfo_ConstructTxERC20Request.Size(m)
}
func (m *ConstructTxERC20Request) XXX_DiscardUnknown() {
	xxx_messageInfo_ConstructTxERC20Request.DiscardUnknown(m)
}

var xxx_messageInfo_ConstructTxERC20Request proto.InternalMessageInfo

func (m *ConstructTxERC20Request) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ConstructTxERC20Request) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ConstructTxERC20Request) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *ConstructTxERC20Request) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

type ConstructTxERC20Reply struct {
	UnsignedTxHex        string   `protobuf:"bytes,1,opt,name=UnsignedTxHex" json:"UnsignedTxHex,omitempty"`
	ChainID              string   `protobuf:"bytes,2,opt,name=ChainID" json:"ChainID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConstructTxERC20Reply) Reset()         { *m = ConstructTxERC20Reply{} }
func (m *ConstructTxERC20Reply) String() string { return proto.CompactTextString(m) }
func (*ConstructTxERC20Reply) ProtoMessage()    {}
func (*ConstructTxERC20Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_972a31c8e33d20d2, []int{21}
}
func (m *ConstructTxERC20Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConstructTxERC20Reply.Unmarshal(m, b)
}
func (m *ConstructTxERC20Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConstructTxERC20Reply.Marshal(b, m, deterministic)
}
func (dst *ConstructTxERC20Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConstructTxERC20Reply.Merge(dst, src)
}
func (m *ConstructTxERC20Reply) XXX_Size() int {
	return xxx_messageInfo_ConstructTxERC20Reply.Size(m)
}
func (m *ConstructTxERC20Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConstructTxERC20Reply.DiscardUnknown(m)
}

var xxx_messageInfo_ConstructTxERC20Reply proto.InternalMessageInfo

func (m *ConstructTxERC20Reply) GetUnsignedTxHex() string {
	if m != nil {
		return m.UnsignedTxHex
	}
	return ""
}

func (m *ConstructTxERC20Reply) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func init() {
	proto.RegisterType((*BitcoincoreBlockRequest)(nil), "pb.BitcoincoreBlockRequest")
	proto.RegisterType((*BitcoincoreBlockReply)(nil), "pb.BitcoincoreBlockReply")
	proto.RegisterType((*QueryOmniPropertyRequest)(nil), "pb.QueryOmniPropertyRequest")
	proto.RegisterType((*OmniProperty)(nil), "pb.OmniProperty")
	proto.RegisterType((*QueryOmniPropertyReply)(nil), "pb.QueryOmniPropertyReply")
	proto.RegisterType((*ERC20TokenInfoRequest)(nil), "pb.ERC20TokenInfoRequest")
	proto.RegisterType((*ERC20Token)(nil), "pb.ERC20Token")
	proto.RegisterType((*ERC20TokenInfoReply)(nil), "pb.ERC20TokenInfoReply")
	proto.RegisterType((*ConstructTxBTCRequest)(nil), "pb.ConstructTxBTCRequest")
	proto.RegisterType((*ConstructTxBTCReply)(nil), "pb.ConstructTxBTCReply")
	proto.RegisterType((*SendBTCTxRequest)(nil), "pb.SendBTCTxRequest")
	proto.RegisterType((*SendBTCTxReply)(nil), "pb.SendBTCTxReply")
	proto.RegisterType((*QueryBalanceRequest)(nil), "pb.QueryBalanceRequest")
	proto.RegisterType((*QueryBalanceReply)(nil), "pb.QueryBalanceReply")
	proto.RegisterType((*WalletValidateRequest)(nil), "pb.WalletValidateRequest")
	proto.RegisterType((*WalletValidateReply)(nil), "pb.WalletValidateReply")
	proto.RegisterType((*ConstructTxETHRequest)(nil), "pb.ConstructTxETHRequest")
	proto.RegisterType((*ConstructTxETHReply)(nil), "pb.ConstructTxETHReply")
	proto.RegisterType((*SendETHTxRequest)(nil), "pb.SendETHTxRequest")
	proto.RegisterType((*SendETHTxReply)(nil), "pb.SendETHTxReply")
	proto.RegisterType((*ConstructTxERC20Request)(nil), "pb.ConstructTxERC20Request")
	proto.RegisterType((*ConstructTxERC20Reply)(nil), "pb.ConstructTxERC20Reply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChainsQueryClient is the client API for ChainsQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChainsQueryClient interface {
	BitcoincoreBlock(ctx context.Context, in *BitcoincoreBlockRequest, opts ...grpc.CallOption) (*BitcoincoreBlockReply, error)
	QueryOmniProperty(ctx context.Context, in *QueryOmniPropertyRequest, opts ...grpc.CallOption) (*QueryOmniPropertyReply, error)
	ERC20TokenInfo(ctx context.Context, in *ERC20TokenInfoRequest, opts ...grpc.CallOption) (*ERC20TokenInfoReply, error)
	ConstructTxBTC(ctx context.Context, in *ConstructTxBTCRequest, opts ...grpc.CallOption) (*ConstructTxBTCReply, error)
	SendBTCTx(ctx context.Context, in *SendBTCTxRequest, opts ...grpc.CallOption) (*SendBTCTxReply, error)
	QueryBalance(ctx context.Context, in *QueryBalanceRequest, opts ...grpc.CallOption) (*QueryBalanceReply, error)
	WalletValidate(ctx context.Context, in *WalletValidateRequest, opts ...grpc.CallOption) (*WalletValidateReply, error)
	ConstructTxETH(ctx context.Context, in *ConstructTxETHRequest, opts ...grpc.CallOption) (*ConstructTxETHReply, error)
	SendETHTx(ctx context.Context, in *SendETHTxRequest, opts ...grpc.CallOption) (*SendETHTxReply, error)
	ConstructTxERC20(ctx context.Context, in *ConstructTxERC20Request, opts ...grpc.CallOption) (*ConstructTxERC20Reply, error)
}

type chainsQueryClient struct {
	cc *grpc.ClientConn
}

func NewChainsQueryClient(cc *grpc.ClientConn) ChainsQueryClient {
	return &chainsQueryClient{cc}
}

func (c *chainsQueryClient) BitcoincoreBlock(ctx context.Context, in *BitcoincoreBlockRequest, opts ...grpc.CallOption) (*BitcoincoreBlockReply, error) {
	out := new(BitcoincoreBlockReply)
	err := c.cc.Invoke(ctx, "/pb.ChainsQuery/BitcoincoreBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainsQueryClient) QueryOmniProperty(ctx context.Context, in *QueryOmniPropertyRequest, opts ...grpc.CallOption) (*QueryOmniPropertyReply, error) {
	out := new(QueryOmniPropertyReply)
	err := c.cc.Invoke(ctx, "/pb.ChainsQuery/QueryOmniProperty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainsQueryClient) ERC20TokenInfo(ctx context.Context, in *ERC20TokenInfoRequest, opts ...grpc.CallOption) (*ERC20TokenInfoReply, error) {
	out := new(ERC20TokenInfoReply)
	err := c.cc.Invoke(ctx, "/pb.ChainsQuery/ERC20TokenInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainsQueryClient) ConstructTxBTC(ctx context.Context, in *ConstructTxBTCRequest, opts ...grpc.CallOption) (*ConstructTxBTCReply, error) {
	out := new(ConstructTxBTCReply)
	err := c.cc.Invoke(ctx, "/pb.ChainsQuery/ConstructTxBTC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainsQueryClient) SendBTCTx(ctx context.Context, in *SendBTCTxRequest, opts ...grpc.CallOption) (*SendBTCTxReply, error) {
	out := new(SendBTCTxReply)
	err := c.cc.Invoke(ctx, "/pb.ChainsQuery/SendBTCTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainsQueryClient) QueryBalance(ctx context.Context, in *QueryBalanceRequest, opts ...grpc.CallOption) (*QueryBalanceReply, error) {
	out := new(QueryBalanceReply)
	err := c.cc.Invoke(ctx, "/pb.ChainsQuery/QueryBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainsQueryClient) WalletValidate(ctx context.Context, in *WalletValidateRequest, opts ...grpc.CallOption) (*WalletValidateReply, error) {
	out := new(WalletValidateReply)
	err := c.cc.Invoke(ctx, "/pb.ChainsQuery/WalletValidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainsQueryClient) ConstructTxETH(ctx context.Context, in *ConstructTxETHRequest, opts ...grpc.CallOption) (*ConstructTxETHReply, error) {
	out := new(ConstructTxETHReply)
	err := c.cc.Invoke(ctx, "/pb.ChainsQuery/ConstructTxETH", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainsQueryClient) SendETHTx(ctx context.Context, in *SendETHTxRequest, opts ...grpc.CallOption) (*SendETHTxReply, error) {
	out := new(SendETHTxReply)
	err := c.cc.Invoke(ctx, "/pb.ChainsQuery/SendETHTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainsQueryClient) ConstructTxERC20(ctx context.Context, in *ConstructTxERC20Request, opts ...grpc.CallOption) (*ConstructTxERC20Reply, error) {
	out := new(ConstructTxERC20Reply)
	err := c.cc.Invoke(ctx, "/pb.ChainsQuery/ConstructTxERC20", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainsQueryServer is the server API for ChainsQuery service.
type ChainsQueryServer interface {
	BitcoincoreBlock(context.Context, *BitcoincoreBlockRequest) (*BitcoincoreBlockReply, error)
	QueryOmniProperty(context.Context, *QueryOmniPropertyRequest) (*QueryOmniPropertyReply, error)
	ERC20TokenInfo(context.Context, *ERC20TokenInfoRequest) (*ERC20TokenInfoReply, error)
	ConstructTxBTC(context.Context, *ConstructTxBTCRequest) (*ConstructTxBTCReply, error)
	SendBTCTx(context.Context, *SendBTCTxRequest) (*SendBTCTxReply, error)
	QueryBalance(context.Context, *QueryBalanceRequest) (*QueryBalanceReply, error)
	WalletValidate(context.Context, *WalletValidateRequest) (*WalletValidateReply, error)
	ConstructTxETH(context.Context, *ConstructTxETHRequest) (*ConstructTxETHReply, error)
	SendETHTx(context.Context, *SendETHTxRequest) (*SendETHTxReply, error)
	ConstructTxERC20(context.Context, *ConstructTxERC20Request) (*ConstructTxERC20Reply, error)
}

func RegisterChainsQueryServer(s *grpc.Server, srv ChainsQueryServer) {
	s.RegisterService(&_ChainsQuery_serviceDesc, srv)
}

func _ChainsQuery_BitcoincoreBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BitcoincoreBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainsQueryServer).BitcoincoreBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChainsQuery/BitcoincoreBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainsQueryServer).BitcoincoreBlock(ctx, req.(*BitcoincoreBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainsQuery_QueryOmniProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOmniPropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainsQueryServer).QueryOmniProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChainsQuery/QueryOmniProperty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainsQueryServer).QueryOmniProperty(ctx, req.(*QueryOmniPropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainsQuery_ERC20TokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ERC20TokenInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainsQueryServer).ERC20TokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChainsQuery/ERC20TokenInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainsQueryServer).ERC20TokenInfo(ctx, req.(*ERC20TokenInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainsQuery_ConstructTxBTC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConstructTxBTCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainsQueryServer).ConstructTxBTC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChainsQuery/ConstructTxBTC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainsQueryServer).ConstructTxBTC(ctx, req.(*ConstructTxBTCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainsQuery_SendBTCTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBTCTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainsQueryServer).SendBTCTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChainsQuery/SendBTCTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainsQueryServer).SendBTCTx(ctx, req.(*SendBTCTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainsQuery_QueryBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainsQueryServer).QueryBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChainsQuery/QueryBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainsQueryServer).QueryBalance(ctx, req.(*QueryBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainsQuery_WalletValidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainsQueryServer).WalletValidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChainsQuery/WalletValidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainsQueryServer).WalletValidate(ctx, req.(*WalletValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainsQuery_ConstructTxETH_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConstructTxETHRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainsQueryServer).ConstructTxETH(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChainsQuery/ConstructTxETH",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainsQueryServer).ConstructTxETH(ctx, req.(*ConstructTxETHRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainsQuery_SendETHTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendETHTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainsQueryServer).SendETHTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChainsQuery/SendETHTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainsQueryServer).SendETHTx(ctx, req.(*SendETHTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainsQuery_ConstructTxERC20_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConstructTxERC20Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainsQueryServer).ConstructTxERC20(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChainsQuery/ConstructTxERC20",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainsQueryServer).ConstructTxERC20(ctx, req.(*ConstructTxERC20Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChainsQuery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ChainsQuery",
	HandlerType: (*ChainsQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BitcoincoreBlock",
			Handler:    _ChainsQuery_BitcoincoreBlock_Handler,
		},
		{
			MethodName: "QueryOmniProperty",
			Handler:    _ChainsQuery_QueryOmniProperty_Handler,
		},
		{
			MethodName: "ERC20TokenInfo",
			Handler:    _ChainsQuery_ERC20TokenInfo_Handler,
		},
		{
			MethodName: "ConstructTxBTC",
			Handler:    _ChainsQuery_ConstructTxBTC_Handler,
		},
		{
			MethodName: "SendBTCTx",
			Handler:    _ChainsQuery_SendBTCTx_Handler,
		},
		{
			MethodName: "QueryBalance",
			Handler:    _ChainsQuery_QueryBalance_Handler,
		},
		{
			MethodName: "WalletValidate",
			Handler:    _ChainsQuery_WalletValidate_Handler,
		},
		{
			MethodName: "ConstructTxETH",
			Handler:    _ChainsQuery_ConstructTxETH_Handler,
		},
		{
			MethodName: "SendETHTx",
			Handler:    _ChainsQuery_SendETHTx_Handler,
		},
		{
			MethodName: "ConstructTxERC20",
			Handler:    _ChainsQuery_ConstructTxERC20_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chains_query.proto",
}

func init() { proto.RegisterFile("chains_query.proto", fileDescriptor_chains_query_972a31c8e33d20d2) }

var fileDescriptor_chains_query_972a31c8e33d20d2 = []byte{
	// 869 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4b, 0x6f, 0xe3, 0x36,
	0x10, 0x46, 0x1c, 0x6f, 0x12, 0x4f, 0xb2, 0xa9, 0xcb, 0xd4, 0xb1, 0xa2, 0x06, 0x45, 0x40, 0xe4,
	0x90, 0x4b, 0x83, 0x22, 0xbb, 0xbd, 0xf4, 0x50, 0x60, 0xfd, 0x48, 0x93, 0x45, 0xf7, 0x51, 0x59,
	0xd9, 0x45, 0x4f, 0x05, 0x25, 0xb1, 0x2e, 0xb1, 0x32, 0xa9, 0x48, 0x74, 0x61, 0xf7, 0x17, 0xf4,
	0x37, 0xf5, 0xd7, 0x15, 0xa4, 0xa8, 0x07, 0x65, 0xb9, 0x28, 0x16, 0xb9, 0x71, 0xbe, 0x99, 0xf9,
	0x3c, 0x6f, 0x19, 0x50, 0xf8, 0x07, 0x61, 0x3c, 0xfb, 0xed, 0x71, 0x49, 0xd3, 0xf5, 0x75, 0x92,
	0x0a, 0x29, 0x50, 0x27, 0x09, 0xf0, 0x19, 0x0c, 0x47, 0x4c, 0x86, 0x82, 0xf1, 0x50, 0xa4, 0x74,
	0x14, 0x8b, 0xf0, 0x93, 0x47, 0x1f, 0x97, 0x34, 0x93, 0x78, 0x08, 0x83, 0x4d, 0x55, 0x12, 0xaf,
	0xf1, 0x0f, 0xe0, 0xfc, 0xa2, 0x68, 0xde, 0x2d, 0x38, 0x7b, 0x9f, 0x8a, 0x84, 0xa6, 0x72, 0x6d,
	0x9c, 0xd0, 0x37, 0x00, 0x89, 0x81, 0x58, 0xe4, 0xec, 0x5c, 0xec, 0x5c, 0xed, 0x7a, 0x35, 0x04,
	0xff, 0xbd, 0x0b, 0x47, 0x75, 0x3f, 0xe5, 0xf0, 0x7e, 0xc3, 0xa1, 0x42, 0x10, 0x82, 0xee, 0x5b,
	0xb2, 0xa0, 0x4e, 0xe7, 0x62, 0xe7, 0xaa, 0xe7, 0xe9, 0x37, 0x72, 0xe1, 0x60, 0x4c, 0x24, 0x9d,
	0x8b, 0x74, 0xed, 0xec, 0x6a, 0xbc, 0x94, 0xd1, 0x05, 0x1c, 0xce, 0x96, 0x41, 0x58, 0xa8, 0xbb,
	0x5a, 0x5d, 0x87, 0x50, 0x1f, 0x76, 0x1f, 0xbc, 0x9f, 0x9d, 0x67, 0x5a, 0xa3, 0x9e, 0xe8, 0x1c,
	0x7a, 0x13, 0xf6, 0x27, 0xcb, 0x58, 0x10, 0x53, 0x67, 0xef, 0x62, 0xe7, 0xea, 0xc0, 0xab, 0x00,
	0x74, 0x0a, 0x7b, 0xf7, 0x59, 0xb6, 0xa4, 0xa9, 0xb3, 0xaf, 0x5d, 0x8c, 0x84, 0x30, 0x1c, 0x8d,
	0x53, 0x4a, 0x24, 0x13, 0x5c, 0xae, 0x58, 0xe4, 0x1c, 0x68, 0xad, 0x85, 0xa1, 0x4b, 0x78, 0x7e,
	0xcb, 0x56, 0x34, 0x62, 0x59, 0xb6, 0x24, 0x3c, 0xa4, 0x4e, 0x4f, 0xb3, 0xdb, 0x20, 0xba, 0x82,
	0x2f, 0xde, 0x10, 0x4e, 0xe6, 0x35, 0x3b, 0xd0, 0x76, 0x4d, 0x58, 0x59, 0xde, 0xa6, 0x94, 0xfe,
	0xc5, 0xf8, 0x9c, 0x72, 0x12, 0xc4, 0x34, 0x72, 0x0e, 0x73, 0xcb, 0x06, 0xac, 0xea, 0xe0, 0x0b,
	0x49, 0x62, 0x29, 0x3e, 0x51, 0x9e, 0x39, 0x47, 0x79, 0x1d, 0x6a, 0x10, 0x7e, 0x0b, 0xa7, 0x2d,
	0x6d, 0x4c, 0xe2, 0x35, 0x7a, 0x69, 0xf7, 0x48, 0x77, 0xe5, 0xf0, 0xa6, 0x7f, 0x9d, 0x04, 0xd7,
	0x96, 0xb1, 0x65, 0x85, 0x5f, 0xc0, 0x60, 0xea, 0x8d, 0x6f, 0xbe, 0xf3, 0x15, 0xfd, 0x3d, 0xff,
	0x5d, 0x14, 0x33, 0xe1, 0xc2, 0x81, 0xc6, 0xee, 0xe8, 0x4a, 0x53, 0xf5, 0xbc, 0x52, 0xc6, 0x1c,
	0xa0, 0x72, 0x52, 0xa5, 0x9e, 0xad, 0x17, 0x81, 0x88, 0x8d, 0x9d, 0x91, 0xb6, 0x0d, 0xc1, 0x84,
	0x86, 0x6c, 0x41, 0xe2, 0x4c, 0x0f, 0x41, 0xd7, 0x2b, 0x65, 0xe4, 0xc0, 0xfe, 0xab, 0x28, 0x4a,
	0x69, 0x96, 0x99, 0x01, 0x28, 0x44, 0x3c, 0x85, 0x93, 0x66, 0x90, 0x2a, 0xe3, 0xeb, 0x7a, 0x18,
	0x26, 0xdf, 0x63, 0x95, 0x6f, 0x85, 0x7a, 0x35, 0x0b, 0x3c, 0x83, 0xc1, 0x58, 0xf0, 0x4c, 0xa6,
	0xcb, 0x50, 0xfa, 0xab, 0x91, 0x3f, 0x2e, 0x72, 0x45, 0xd0, 0xbd, 0x4d, 0xc5, 0xc2, 0xc4, 0xaf,
	0xdf, 0xe8, 0x18, 0x3a, 0xbe, 0x30, 0xb1, 0x77, 0x7c, 0xa1, 0xb2, 0x7c, 0xb5, 0x10, 0x4b, 0x2e,
	0xcd, 0xf0, 0x1a, 0x09, 0xff, 0x0a, 0x27, 0x4d, 0x52, 0x15, 0xdb, 0x25, 0x3c, 0x7f, 0xe0, 0x19,
	0x9b, 0x73, 0x1a, 0xf9, 0xab, 0xaa, 0x86, 0x36, 0xa8, 0x66, 0xf8, 0x03, 0xe3, 0x86, 0xb7, 0xa3,
	0xd7, 0xa8, 0x02, 0xf0, 0x4b, 0xe8, 0xcf, 0x28, 0x8f, 0x46, 0xfe, 0xd8, 0x5f, 0x15, 0xa1, 0xaa,
	0x4d, 0xd9, 0x60, 0xad, 0x43, 0xf8, 0x12, 0x8e, 0x6b, 0x5e, 0x2a, 0x16, 0x04, 0x5d, 0x7f, 0x75,
	0x3f, 0x29, 0xd2, 0x53, 0x6f, 0xfc, 0x13, 0x9c, 0xe8, 0x39, 0x1a, 0x91, 0x58, 0xcd, 0x68, 0x41,
	0x7f, 0x0a, 0x7b, 0x99, 0xd5, 0xcb, 0x5c, 0x52, 0xbd, 0x21, 0xa6, 0x37, 0x79, 0x49, 0x0a, 0x11,
	0x7f, 0x0b, 0x5f, 0xda, 0x44, 0xea, 0x17, 0x1d, 0xd8, 0x0f, 0x72, 0xd9, 0xf0, 0x14, 0x22, 0x7e,
	0x07, 0x83, 0x8f, 0x24, 0x8e, 0xa9, 0xfc, 0x40, 0x62, 0x16, 0x11, 0x59, 0xfe, 0xf2, 0x39, 0xf4,
	0xf4, 0xb5, 0xd3, 0x23, 0x93, 0x3b, 0x55, 0xc0, 0x7f, 0xfc, 0xfe, 0x00, 0x4e, 0x9a, 0x84, 0xea,
	0xdc, 0xd9, 0xbd, 0x9e, 0xfa, 0x77, 0x4f, 0xd1, 0xeb, 0x07, 0xab, 0xd7, 0x9a, 0xf4, 0xff, 0xf7,
	0xda, 0x81, 0xfd, 0xb1, 0xca, 0xe7, 0x7e, 0x52, 0xa4, 0x60, 0xc4, 0xa2, 0xcf, 0x53, 0xff, 0xee,
	0x33, 0xfa, 0x6c, 0xbc, 0xb6, 0xf5, 0xf9, 0x11, 0x86, 0xf5, 0x90, 0xd5, 0x32, 0x3c, 0x41, 0x25,
	0xf4, 0x31, 0x17, 0x5c, 0xa6, 0x24, 0x94, 0x66, 0x59, 0x4b, 0x19, 0x7f, 0xb4, 0x4b, 0x9f, 0xff,
	0xe4, 0x13, 0xd4, 0xe9, 0xe6, 0x9f, 0x67, 0x70, 0xa8, 0xdf, 0x99, 0x9e, 0x38, 0xf4, 0x1a, 0xfa,
	0xcd, 0x6f, 0x1d, 0xfa, 0x5a, 0xed, 0xff, 0x96, 0x8f, 0xa3, 0x7b, 0xd6, 0xae, 0x54, 0xb1, 0xbd,
	0x31, 0x63, 0x6c, 0x7d, 0xe6, 0xce, 0x95, 0xfd, 0xb6, 0xaf, 0xa6, 0xeb, 0x6e, 0xd1, 0x2a, 0xba,
	0x09, 0x1c, 0xdb, 0x17, 0x0b, 0x9d, 0xd9, 0x87, 0xa9, 0x76, 0x6a, 0xdd, 0x61, 0x9b, 0xca, 0xb0,
	0xd8, 0xb7, 0x25, 0x67, 0x69, 0x3d, 0x62, 0x39, 0x4b, 0xdb, 0x29, 0xfa, 0x1e, 0x7a, 0xe5, 0x41,
	0x40, 0x5f, 0x29, 0xab, 0xe6, 0x55, 0x71, 0x51, 0x03, 0x55, 0x6e, 0x3f, 0xc2, 0x51, 0x7d, 0xb1,
	0xd1, 0xb0, 0x4c, 0xd7, 0xbe, 0x19, 0xee, 0x60, 0x53, 0x61, 0x82, 0xb7, 0x17, 0x33, 0x0f, 0xbe,
	0x75, 0xfb, 0xf3, 0xe0, 0x5b, 0xf6, 0xb8, 0x51, 0x82, 0xa9, 0x7f, 0xb7, 0x51, 0x82, 0x6a, 0xb7,
	0x37, 0x4a, 0x50, 0x6e, 0xa8, 0x29, 0x81, 0xde, 0x95, 0xaa, 0x04, 0xf5, 0x85, 0xab, 0x4a, 0x50,
	0x5b, 0xa8, 0xd7, 0xd0, 0x6f, 0x4e, 0x72, 0x3e, 0x60, 0x5b, 0x56, 0xca, 0x3d, 0x6b, 0x57, 0x26,
	0xf1, 0x3a, 0xd8, 0xd3, 0x7f, 0xdf, 0x5e, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x24, 0xcb,
	0x41, 0xd4, 0x09, 0x00, 0x00,
}
