// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chains_query.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BitcoincoreBlockRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BitcoincoreBlockRequest) Reset()         { *m = BitcoincoreBlockRequest{} }
func (m *BitcoincoreBlockRequest) String() string { return proto.CompactTextString(m) }
func (*BitcoincoreBlockRequest) ProtoMessage()    {}
func (*BitcoincoreBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_bd2c8763db3d27bd, []int{0}
}
func (m *BitcoincoreBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitcoincoreBlockRequest.Unmarshal(m, b)
}
func (m *BitcoincoreBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitcoincoreBlockRequest.Marshal(b, m, deterministic)
}
func (dst *BitcoincoreBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitcoincoreBlockRequest.Merge(dst, src)
}
func (m *BitcoincoreBlockRequest) XXX_Size() int {
	return xxx_messageInfo_BitcoincoreBlockRequest.Size(m)
}
func (m *BitcoincoreBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BitcoincoreBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BitcoincoreBlockRequest proto.InternalMessageInfo

type BitcoincoreBlockReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BitcoincoreBlockReply) Reset()         { *m = BitcoincoreBlockReply{} }
func (m *BitcoincoreBlockReply) String() string { return proto.CompactTextString(m) }
func (*BitcoincoreBlockReply) ProtoMessage()    {}
func (*BitcoincoreBlockReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_bd2c8763db3d27bd, []int{1}
}
func (m *BitcoincoreBlockReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitcoincoreBlockReply.Unmarshal(m, b)
}
func (m *BitcoincoreBlockReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitcoincoreBlockReply.Marshal(b, m, deterministic)
}
func (dst *BitcoincoreBlockReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitcoincoreBlockReply.Merge(dst, src)
}
func (m *BitcoincoreBlockReply) XXX_Size() int {
	return xxx_messageInfo_BitcoincoreBlockReply.Size(m)
}
func (m *BitcoincoreBlockReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BitcoincoreBlockReply.DiscardUnknown(m)
}

var xxx_messageInfo_BitcoincoreBlockReply proto.InternalMessageInfo

type QueryOmniPropertyRequest struct {
	Propertyid           int64    `protobuf:"varint,1,opt,name=propertyid" json:"propertyid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOmniPropertyRequest) Reset()         { *m = QueryOmniPropertyRequest{} }
func (m *QueryOmniPropertyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOmniPropertyRequest) ProtoMessage()    {}
func (*QueryOmniPropertyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_bd2c8763db3d27bd, []int{2}
}
func (m *QueryOmniPropertyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOmniPropertyRequest.Unmarshal(m, b)
}
func (m *QueryOmniPropertyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOmniPropertyRequest.Marshal(b, m, deterministic)
}
func (dst *QueryOmniPropertyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOmniPropertyRequest.Merge(dst, src)
}
func (m *QueryOmniPropertyRequest) XXX_Size() int {
	return xxx_messageInfo_QueryOmniPropertyRequest.Size(m)
}
func (m *QueryOmniPropertyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOmniPropertyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOmniPropertyRequest proto.InternalMessageInfo

func (m *QueryOmniPropertyRequest) GetPropertyid() int64 {
	if m != nil {
		return m.Propertyid
	}
	return 0
}

type OmniProperty struct {
	Propertyid           int64    `protobuf:"varint,1,opt,name=Propertyid" json:"Propertyid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=Category" json:"Category,omitempty"`
	Subcategory          string   `protobuf:"bytes,4,opt,name=Subcategory" json:"Subcategory,omitempty"`
	URL                  string   `protobuf:"bytes,5,opt,name=URL" json:"URL,omitempty"`
	Divisible            bool     `protobuf:"varint,6,opt,name=Divisible" json:"Divisible,omitempty"`
	Issuer               string   `protobuf:"bytes,7,opt,name=Issuer" json:"Issuer,omitempty"`
	Creationtxid         string   `protobuf:"bytes,8,opt,name=Creationtxid" json:"Creationtxid,omitempty"`
	Fixedissuance        bool     `protobuf:"varint,9,opt,name=Fixedissuance" json:"Fixedissuance,omitempty"`
	Managedissuance      bool     `protobuf:"varint,10,opt,name=Managedissuance" json:"Managedissuance,omitempty"`
	Freezingenabled      bool     `protobuf:"varint,11,opt,name=Freezingenabled" json:"Freezingenabled,omitempty"`
	Totaltokens          string   `protobuf:"bytes,12,opt,name=Totaltokens" json:"Totaltokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OmniProperty) Reset()         { *m = OmniProperty{} }
func (m *OmniProperty) String() string { return proto.CompactTextString(m) }
func (*OmniProperty) ProtoMessage()    {}
func (*OmniProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_bd2c8763db3d27bd, []int{3}
}
func (m *OmniProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OmniProperty.Unmarshal(m, b)
}
func (m *OmniProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OmniProperty.Marshal(b, m, deterministic)
}
func (dst *OmniProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OmniProperty.Merge(dst, src)
}
func (m *OmniProperty) XXX_Size() int {
	return xxx_messageInfo_OmniProperty.Size(m)
}
func (m *OmniProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_OmniProperty.DiscardUnknown(m)
}

var xxx_messageInfo_OmniProperty proto.InternalMessageInfo

func (m *OmniProperty) GetPropertyid() int64 {
	if m != nil {
		return m.Propertyid
	}
	return 0
}

func (m *OmniProperty) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OmniProperty) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *OmniProperty) GetSubcategory() string {
	if m != nil {
		return m.Subcategory
	}
	return ""
}

func (m *OmniProperty) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *OmniProperty) GetDivisible() bool {
	if m != nil {
		return m.Divisible
	}
	return false
}

func (m *OmniProperty) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *OmniProperty) GetCreationtxid() string {
	if m != nil {
		return m.Creationtxid
	}
	return ""
}

func (m *OmniProperty) GetFixedissuance() bool {
	if m != nil {
		return m.Fixedissuance
	}
	return false
}

func (m *OmniProperty) GetManagedissuance() bool {
	if m != nil {
		return m.Managedissuance
	}
	return false
}

func (m *OmniProperty) GetFreezingenabled() bool {
	if m != nil {
		return m.Freezingenabled
	}
	return false
}

func (m *OmniProperty) GetTotaltokens() string {
	if m != nil {
		return m.Totaltokens
	}
	return ""
}

type QueryOmniPropertyReply struct {
	OmniProperty         *OmniProperty `protobuf:"bytes,1,opt,name=OmniProperty" json:"OmniProperty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QueryOmniPropertyReply) Reset()         { *m = QueryOmniPropertyReply{} }
func (m *QueryOmniPropertyReply) String() string { return proto.CompactTextString(m) }
func (*QueryOmniPropertyReply) ProtoMessage()    {}
func (*QueryOmniPropertyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_bd2c8763db3d27bd, []int{4}
}
func (m *QueryOmniPropertyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOmniPropertyReply.Unmarshal(m, b)
}
func (m *QueryOmniPropertyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOmniPropertyReply.Marshal(b, m, deterministic)
}
func (dst *QueryOmniPropertyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOmniPropertyReply.Merge(dst, src)
}
func (m *QueryOmniPropertyReply) XXX_Size() int {
	return xxx_messageInfo_QueryOmniPropertyReply.Size(m)
}
func (m *QueryOmniPropertyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOmniPropertyReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOmniPropertyReply proto.InternalMessageInfo

func (m *QueryOmniPropertyReply) GetOmniProperty() *OmniProperty {
	if m != nil {
		return m.OmniProperty
	}
	return nil
}

type ERC20TokenInfoRequest struct {
	TokenHex             string   `protobuf:"bytes,1,opt,name=TokenHex" json:"TokenHex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ERC20TokenInfoRequest) Reset()         { *m = ERC20TokenInfoRequest{} }
func (m *ERC20TokenInfoRequest) String() string { return proto.CompactTextString(m) }
func (*ERC20TokenInfoRequest) ProtoMessage()    {}
func (*ERC20TokenInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_bd2c8763db3d27bd, []int{5}
}
func (m *ERC20TokenInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ERC20TokenInfoRequest.Unmarshal(m, b)
}
func (m *ERC20TokenInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ERC20TokenInfoRequest.Marshal(b, m, deterministic)
}
func (dst *ERC20TokenInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ERC20TokenInfoRequest.Merge(dst, src)
}
func (m *ERC20TokenInfoRequest) XXX_Size() int {
	return xxx_messageInfo_ERC20TokenInfoRequest.Size(m)
}
func (m *ERC20TokenInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ERC20TokenInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ERC20TokenInfoRequest proto.InternalMessageInfo

func (m *ERC20TokenInfoRequest) GetTokenHex() string {
	if m != nil {
		return m.TokenHex
	}
	return ""
}

type ERC20Token struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=Symbol" json:"Symbol,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Decimals             uint64   `protobuf:"varint,3,opt,name=Decimals" json:"Decimals,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=Address" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ERC20Token) Reset()         { *m = ERC20Token{} }
func (m *ERC20Token) String() string { return proto.CompactTextString(m) }
func (*ERC20Token) ProtoMessage()    {}
func (*ERC20Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_bd2c8763db3d27bd, []int{6}
}
func (m *ERC20Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ERC20Token.Unmarshal(m, b)
}
func (m *ERC20Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ERC20Token.Marshal(b, m, deterministic)
}
func (dst *ERC20Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ERC20Token.Merge(dst, src)
}
func (m *ERC20Token) XXX_Size() int {
	return xxx_messageInfo_ERC20Token.Size(m)
}
func (m *ERC20Token) XXX_DiscardUnknown() {
	xxx_messageInfo_ERC20Token.DiscardUnknown(m)
}

var xxx_messageInfo_ERC20Token proto.InternalMessageInfo

func (m *ERC20Token) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ERC20Token) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ERC20Token) GetDecimals() uint64 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *ERC20Token) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ERC20TokenInfoReply struct {
	ERC20Token           *ERC20Token `protobuf:"bytes,1,opt,name=ERC20Token" json:"ERC20Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ERC20TokenInfoReply) Reset()         { *m = ERC20TokenInfoReply{} }
func (m *ERC20TokenInfoReply) String() string { return proto.CompactTextString(m) }
func (*ERC20TokenInfoReply) ProtoMessage()    {}
func (*ERC20TokenInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_bd2c8763db3d27bd, []int{7}
}
func (m *ERC20TokenInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ERC20TokenInfoReply.Unmarshal(m, b)
}
func (m *ERC20TokenInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ERC20TokenInfoReply.Marshal(b, m, deterministic)
}
func (dst *ERC20TokenInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ERC20TokenInfoReply.Merge(dst, src)
}
func (m *ERC20TokenInfoReply) XXX_Size() int {
	return xxx_messageInfo_ERC20TokenInfoReply.Size(m)
}
func (m *ERC20TokenInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ERC20TokenInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_ERC20TokenInfoReply proto.InternalMessageInfo

func (m *ERC20TokenInfoReply) GetERC20Token() *ERC20Token {
	if m != nil {
		return m.ERC20Token
	}
	return nil
}

type ConstructTxBTCRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=From" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=To" json:"To,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=Amount" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConstructTxBTCRequest) Reset()         { *m = ConstructTxBTCRequest{} }
func (m *ConstructTxBTCRequest) String() string { return proto.CompactTextString(m) }
func (*ConstructTxBTCRequest) ProtoMessage()    {}
func (*ConstructTxBTCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_bd2c8763db3d27bd, []int{8}
}
func (m *ConstructTxBTCRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConstructTxBTCRequest.Unmarshal(m, b)
}
func (m *ConstructTxBTCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConstructTxBTCRequest.Marshal(b, m, deterministic)
}
func (dst *ConstructTxBTCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConstructTxBTCRequest.Merge(dst, src)
}
func (m *ConstructTxBTCRequest) XXX_Size() int {
	return xxx_messageInfo_ConstructTxBTCRequest.Size(m)
}
func (m *ConstructTxBTCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConstructTxBTCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConstructTxBTCRequest proto.InternalMessageInfo

func (m *ConstructTxBTCRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ConstructTxBTCRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ConstructTxBTCRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type ConstructTxBTCReply struct {
	UnsignedTxHex        string   `protobuf:"bytes,1,opt,name=UnsignedTxHex" json:"UnsignedTxHex,omitempty"`
	VinAmount            int64    `protobuf:"varint,2,opt,name=VinAmount" json:"VinAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConstructTxBTCReply) Reset()         { *m = ConstructTxBTCReply{} }
func (m *ConstructTxBTCReply) String() string { return proto.CompactTextString(m) }
func (*ConstructTxBTCReply) ProtoMessage()    {}
func (*ConstructTxBTCReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_chains_query_bd2c8763db3d27bd, []int{9}
}
func (m *ConstructTxBTCReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConstructTxBTCReply.Unmarshal(m, b)
}
func (m *ConstructTxBTCReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConstructTxBTCReply.Marshal(b, m, deterministic)
}
func (dst *ConstructTxBTCReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConstructTxBTCReply.Merge(dst, src)
}
func (m *ConstructTxBTCReply) XXX_Size() int {
	return xxx_messageInfo_ConstructTxBTCReply.Size(m)
}
func (m *ConstructTxBTCReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConstructTxBTCReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConstructTxBTCReply proto.InternalMessageInfo

func (m *ConstructTxBTCReply) GetUnsignedTxHex() string {
	if m != nil {
		return m.UnsignedTxHex
	}
	return ""
}

func (m *ConstructTxBTCReply) GetVinAmount() int64 {
	if m != nil {
		return m.VinAmount
	}
	return 0
}

func init() {
	proto.RegisterType((*BitcoincoreBlockRequest)(nil), "pb.BitcoincoreBlockRequest")
	proto.RegisterType((*BitcoincoreBlockReply)(nil), "pb.BitcoincoreBlockReply")
	proto.RegisterType((*QueryOmniPropertyRequest)(nil), "pb.QueryOmniPropertyRequest")
	proto.RegisterType((*OmniProperty)(nil), "pb.OmniProperty")
	proto.RegisterType((*QueryOmniPropertyReply)(nil), "pb.QueryOmniPropertyReply")
	proto.RegisterType((*ERC20TokenInfoRequest)(nil), "pb.ERC20TokenInfoRequest")
	proto.RegisterType((*ERC20Token)(nil), "pb.ERC20Token")
	proto.RegisterType((*ERC20TokenInfoReply)(nil), "pb.ERC20TokenInfoReply")
	proto.RegisterType((*ConstructTxBTCRequest)(nil), "pb.ConstructTxBTCRequest")
	proto.RegisterType((*ConstructTxBTCReply)(nil), "pb.ConstructTxBTCReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChainsQueryClient is the client API for ChainsQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChainsQueryClient interface {
	BitcoincoreBlock(ctx context.Context, in *BitcoincoreBlockRequest, opts ...grpc.CallOption) (*BitcoincoreBlockReply, error)
	QueryOmniProperty(ctx context.Context, in *QueryOmniPropertyRequest, opts ...grpc.CallOption) (*QueryOmniPropertyReply, error)
	ERC20TokenInfo(ctx context.Context, in *ERC20TokenInfoRequest, opts ...grpc.CallOption) (*ERC20TokenInfoReply, error)
	ConstructTxBTC(ctx context.Context, in *ConstructTxBTCRequest, opts ...grpc.CallOption) (*ConstructTxBTCReply, error)
}

type chainsQueryClient struct {
	cc *grpc.ClientConn
}

func NewChainsQueryClient(cc *grpc.ClientConn) ChainsQueryClient {
	return &chainsQueryClient{cc}
}

func (c *chainsQueryClient) BitcoincoreBlock(ctx context.Context, in *BitcoincoreBlockRequest, opts ...grpc.CallOption) (*BitcoincoreBlockReply, error) {
	out := new(BitcoincoreBlockReply)
	err := c.cc.Invoke(ctx, "/pb.ChainsQuery/BitcoincoreBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainsQueryClient) QueryOmniProperty(ctx context.Context, in *QueryOmniPropertyRequest, opts ...grpc.CallOption) (*QueryOmniPropertyReply, error) {
	out := new(QueryOmniPropertyReply)
	err := c.cc.Invoke(ctx, "/pb.ChainsQuery/QueryOmniProperty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainsQueryClient) ERC20TokenInfo(ctx context.Context, in *ERC20TokenInfoRequest, opts ...grpc.CallOption) (*ERC20TokenInfoReply, error) {
	out := new(ERC20TokenInfoReply)
	err := c.cc.Invoke(ctx, "/pb.ChainsQuery/ERC20TokenInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainsQueryClient) ConstructTxBTC(ctx context.Context, in *ConstructTxBTCRequest, opts ...grpc.CallOption) (*ConstructTxBTCReply, error) {
	out := new(ConstructTxBTCReply)
	err := c.cc.Invoke(ctx, "/pb.ChainsQuery/ConstructTxBTC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainsQueryServer is the server API for ChainsQuery service.
type ChainsQueryServer interface {
	BitcoincoreBlock(context.Context, *BitcoincoreBlockRequest) (*BitcoincoreBlockReply, error)
	QueryOmniProperty(context.Context, *QueryOmniPropertyRequest) (*QueryOmniPropertyReply, error)
	ERC20TokenInfo(context.Context, *ERC20TokenInfoRequest) (*ERC20TokenInfoReply, error)
	ConstructTxBTC(context.Context, *ConstructTxBTCRequest) (*ConstructTxBTCReply, error)
}

func RegisterChainsQueryServer(s *grpc.Server, srv ChainsQueryServer) {
	s.RegisterService(&_ChainsQuery_serviceDesc, srv)
}

func _ChainsQuery_BitcoincoreBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BitcoincoreBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainsQueryServer).BitcoincoreBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChainsQuery/BitcoincoreBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainsQueryServer).BitcoincoreBlock(ctx, req.(*BitcoincoreBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainsQuery_QueryOmniProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOmniPropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainsQueryServer).QueryOmniProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChainsQuery/QueryOmniProperty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainsQueryServer).QueryOmniProperty(ctx, req.(*QueryOmniPropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainsQuery_ERC20TokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ERC20TokenInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainsQueryServer).ERC20TokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChainsQuery/ERC20TokenInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainsQueryServer).ERC20TokenInfo(ctx, req.(*ERC20TokenInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainsQuery_ConstructTxBTC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConstructTxBTCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainsQueryServer).ConstructTxBTC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChainsQuery/ConstructTxBTC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainsQueryServer).ConstructTxBTC(ctx, req.(*ConstructTxBTCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChainsQuery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ChainsQuery",
	HandlerType: (*ChainsQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BitcoincoreBlock",
			Handler:    _ChainsQuery_BitcoincoreBlock_Handler,
		},
		{
			MethodName: "QueryOmniProperty",
			Handler:    _ChainsQuery_QueryOmniProperty_Handler,
		},
		{
			MethodName: "ERC20TokenInfo",
			Handler:    _ChainsQuery_ERC20TokenInfo_Handler,
		},
		{
			MethodName: "ConstructTxBTC",
			Handler:    _ChainsQuery_ConstructTxBTC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chains_query.proto",
}

func init() { proto.RegisterFile("chains_query.proto", fileDescriptor_chains_query_bd2c8763db3d27bd) }

var fileDescriptor_chains_query_bd2c8763db3d27bd = []byte{
	// 591 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xcb, 0x4e, 0xdc, 0x3c,
	0x14, 0xd6, 0x5c, 0x7e, 0x98, 0x39, 0x03, 0xfc, 0xd4, 0x08, 0x30, 0x29, 0xaa, 0x46, 0x11, 0x8b,
	0x59, 0x8d, 0x2a, 0xe8, 0xaa, 0x3b, 0x08, 0xa0, 0x52, 0x15, 0x4a, 0x43, 0xa8, 0xd4, 0x55, 0x95,
	0x8b, 0x3b, 0xb5, 0x48, 0xec, 0x60, 0x3b, 0xd5, 0xa4, 0x4f, 0xd0, 0x07, 0xea, 0x03, 0x56, 0xf6,
	0x78, 0x48, 0x32, 0x97, 0x9d, 0xcf, 0x77, 0xbe, 0xf3, 0xe9, 0xdc, 0x7c, 0x00, 0xc5, 0x3f, 0x43,
	0xca, 0xe4, 0xf7, 0xe7, 0x82, 0x88, 0x72, 0x9c, 0x0b, 0xae, 0x38, 0x6a, 0xe7, 0x91, 0x7b, 0x04,
	0x87, 0x17, 0x54, 0xc5, 0x9c, 0xb2, 0x98, 0x0b, 0x72, 0x91, 0xf2, 0xf8, 0xc9, 0x27, 0xcf, 0x05,
	0x91, 0xca, 0x3d, 0x84, 0xfd, 0x65, 0x57, 0x9e, 0x96, 0xee, 0x7b, 0xc0, 0x5f, 0xb4, 0xcc, 0xe7,
	0x8c, 0xd1, 0x7b, 0xc1, 0x73, 0x22, 0x54, 0x69, 0x83, 0xd0, 0x1b, 0x80, 0xdc, 0x42, 0x34, 0xc1,
	0xad, 0x61, 0x6b, 0xd4, 0xf1, 0x6b, 0x88, 0xfb, 0xa7, 0x03, 0x5b, 0xf5, 0x38, 0x1d, 0x70, 0xbf,
	0x14, 0x50, 0x21, 0x08, 0x41, 0xf7, 0x2e, 0xcc, 0x08, 0x6e, 0x0f, 0x5b, 0xa3, 0xbe, 0x6f, 0xde,
	0xc8, 0x81, 0x9e, 0x17, 0x2a, 0x32, 0xe1, 0xa2, 0xc4, 0x1d, 0x83, 0xbf, 0xd8, 0x68, 0x08, 0x83,
	0x87, 0x22, 0x8a, 0xe7, 0xee, 0xae, 0x71, 0xd7, 0x21, 0xb4, 0x0b, 0x9d, 0x47, 0xff, 0x13, 0xfe,
	0xcf, 0x78, 0xf4, 0x13, 0x1d, 0x43, 0xff, 0x92, 0xfe, 0xa2, 0x92, 0x46, 0x29, 0xc1, 0x1b, 0xc3,
	0xd6, 0xa8, 0xe7, 0x57, 0x00, 0x3a, 0x80, 0x8d, 0x1b, 0x29, 0x0b, 0x22, 0xf0, 0xa6, 0x09, 0xb1,
	0x16, 0x72, 0x61, 0xcb, 0x13, 0x24, 0x54, 0x94, 0x33, 0x35, 0xa5, 0x09, 0xee, 0x19, 0x6f, 0x03,
	0x43, 0x27, 0xb0, 0x7d, 0x4d, 0xa7, 0x24, 0xa1, 0x52, 0x16, 0x21, 0x8b, 0x09, 0xee, 0x1b, 0xf5,
	0x26, 0x88, 0x46, 0xf0, 0xff, 0x6d, 0xc8, 0xc2, 0x49, 0x8d, 0x07, 0x86, 0xb7, 0x08, 0x6b, 0xe6,
	0xb5, 0x20, 0xe4, 0x37, 0x65, 0x13, 0xc2, 0xc2, 0x28, 0x25, 0x09, 0x1e, 0xcc, 0x98, 0x0b, 0xb0,
	0xee, 0x43, 0xc0, 0x55, 0x98, 0x2a, 0xfe, 0x44, 0x98, 0xc4, 0x5b, 0xb3, 0x3e, 0xd4, 0x20, 0xf7,
	0x0e, 0x0e, 0x56, 0x8c, 0x31, 0x4f, 0x4b, 0xf4, 0xae, 0x39, 0x23, 0x33, 0x95, 0xc1, 0xe9, 0xee,
	0x38, 0x8f, 0xc6, 0x0d, 0x72, 0x83, 0xe5, 0x9e, 0xc1, 0xfe, 0x95, 0xef, 0x9d, 0xbe, 0x0d, 0xb4,
	0xfc, 0x0d, 0xfb, 0xc1, 0xe7, 0x3b, 0xe1, 0x40, 0xcf, 0x60, 0x1f, 0xc8, 0xd4, 0x48, 0xf5, 0xfd,
	0x17, 0xdb, 0x65, 0x00, 0x55, 0x90, 0x6e, 0xf5, 0x43, 0x99, 0x45, 0x3c, 0xb5, 0x3c, 0x6b, 0xad,
	0x5b, 0x82, 0x4b, 0x12, 0xd3, 0x2c, 0x4c, 0xa5, 0x59, 0x82, 0xae, 0xff, 0x62, 0x23, 0x0c, 0x9b,
	0xe7, 0x49, 0x22, 0x88, 0x94, 0x76, 0x01, 0xe6, 0xa6, 0x7b, 0x05, 0x7b, 0x8b, 0x49, 0xea, 0x8a,
	0xc7, 0xf5, 0x34, 0x6c, 0xbd, 0x3b, 0xba, 0xde, 0x0a, 0xf5, 0x6b, 0x0c, 0xf7, 0x01, 0xf6, 0x3d,
	0xce, 0xa4, 0x12, 0x45, 0xac, 0x82, 0xe9, 0x45, 0xe0, 0xcd, 0x6b, 0x45, 0xd0, 0xbd, 0x16, 0x3c,
	0xb3, 0xf9, 0x9b, 0x37, 0xda, 0x81, 0x76, 0xc0, 0x6d, 0xee, 0xed, 0x80, 0xeb, 0x2a, 0xcf, 0x33,
	0x5e, 0x30, 0x65, 0x97, 0xd7, 0x5a, 0xee, 0x37, 0xd8, 0x5b, 0x14, 0xd5, 0xb9, 0x9d, 0xc0, 0xf6,
	0x23, 0x93, 0x74, 0xc2, 0x48, 0x12, 0x4c, 0xab, 0x1e, 0x36, 0x41, 0xbd, 0xc3, 0x5f, 0x29, 0xb3,
	0xba, 0x6d, 0xf3, 0x8d, 0x2a, 0xe0, 0xf4, 0x6f, 0x1b, 0x06, 0x9e, 0xb9, 0x00, 0x66, 0xe4, 0xe8,
	0x23, 0xec, 0x2e, 0xfe, 0x6d, 0xf4, 0x5a, 0xd7, 0xbb, 0xe6, 0x18, 0x38, 0x47, 0xab, 0x9d, 0x3a,
	0xbf, 0x5b, 0x78, 0xb5, 0xb4, 0x47, 0xe8, 0x58, 0xf3, 0xd7, 0x5d, 0x09, 0xc7, 0x59, 0xe3, 0xd5,
	0x72, 0x97, 0xb0, 0xd3, 0x9c, 0x10, 0x3a, 0x6a, 0x0e, 0xa2, 0xb6, 0x5a, 0xce, 0xe1, 0x2a, 0x97,
	0x55, 0x69, 0xf6, 0x72, 0xa6, 0xb2, 0x72, 0x68, 0x33, 0x95, 0x15, 0xad, 0x8f, 0x36, 0xcc, 0xa1,
	0x3c, 0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0xff, 0x17, 0xa3, 0x99, 0x3e, 0x05, 0x00, 0x00,
}
