// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	service "trustkeeper-go/app/service/wallet_key/pkg/service"

	endpoint "github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	GenerateMnemonicEndpoint    endpoint.Endpoint
	SignedBitcoincoreTxEndpoint endpoint.Endpoint
	SignedEthereumTxEndpoint    endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.WalletKeyService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		GenerateMnemonicEndpoint:    MakeGenerateMnemonicEndpoint(s),
		SignedBitcoincoreTxEndpoint: MakeSignedBitcoincoreTxEndpoint(s),
		SignedEthereumTxEndpoint:    MakeSignedEthereumTxEndpoint(s),
	}
	for _, m := range mdw["GenerateMnemonic"] {
		eps.GenerateMnemonicEndpoint = m(eps.GenerateMnemonicEndpoint)
	}
	for _, m := range mdw["SignedBitcoincoreTx"] {
		eps.SignedBitcoincoreTxEndpoint = m(eps.SignedBitcoincoreTxEndpoint)
	}
	for _, m := range mdw["SignedEthereumTx"] {
		eps.SignedEthereumTxEndpoint = m(eps.SignedEthereumTxEndpoint)
	}
	return eps
}
