// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "trustkeeper-go/app/service/wallet_key/pkg/endpoint"
	pb "trustkeeper-go/app/service/wallet_key/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	generateMnemonic    grpc.Handler
	signedBitcoincoreTx grpc.Handler
	signedEthereumTx    grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.WalletKeyServer {
	return &grpcServer{
		generateMnemonic:    makeGenerateMnemonicHandler(endpoints, options["GenerateMnemonic"]),
		signedBitcoincoreTx: makeSignedBitcoincoreTxHandler(endpoints, options["SignedBitcoincoreTx"]),
		signedEthereumTx:    makeSignedEthereumTxHandler(endpoints, options["SignedEthereumTx"]),
	}
}
