version: '2'

services:
  bitcoincore:
    container_name: 'bitcoincore_0.15.2'
    build:
      context: ./bitcoincore
      dockerfile: Dockerfile-0-15-2
    ports:
      - "8331:8331"
      - "8431:8431"
    extra_hosts:
      - "outside:172.17.0.1"
    command:
      -server=1
      -listen=1
      -printtoconsole
      -regtest=1
      -port=8331
      -rpcport=8431
      -rpcuser=btcrpc
      -rpcpassword=123456
      -rpcallowip=0.0.0.0/0
      -addnode=omnicore_0.5.0:8332
      -connect=omnicore_0.5.0:8332
      -blocknotify='curl http://172.17.0.1:3001/btc-best-block-notify?hash=%s'
    networks:
      - chainnodes
    volumes:
      - ./bitcoincore/docker-entrypoint.sh:/entrypoint.sh
      - ./bitcoincore/data://home/bitcoin/.bitcoin
  omnicore:
    container_name: 'omnicore_0.5.0'
    build:
      context: ./omnicore
      dockerfile: Dockerfile-0-5-0
    ports:
      - "8332:8332"
      - "8432:8432"
    command:
      -server
      -listen
      -addnode=bitcoincore_0.15.2:8431
      -printtoconsole
      -regtest=1
      -port=8332
      -rpcport=8432
      -rpcuser=btcrpc
      -rpcpassword=123456
      -txindex=1
    networks:
      - chainnodes
    volumes:
      - ./omnicore/docker-entrypoint.sh:/entrypoint.sh
      - ./omnicore/data://home/bitcoin/.bitcoin
  ethereum:
    container_name: 'ethereum'
    image: ethereum/client-go
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
    volumes:
      - ./ethereum/data:/root/.ethereum
    command: "--gcmode archive --rpc --datadir /root/.ethereum --txpool.accountqueue 1000 --rpcaddr 0.0.0.0 --dev --rpcapi admin,db,eth,net,web3,personal,web3,miner,debug,sha3,txpool"
    networks:
      - chainnodes
networks:
  chainnodes:
