// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	grpc "github.com/go-kit/kit/transport/grpc"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
	endpoint "trustkeeper-go/app/service/wallet_management/pkg/endpoint"
	service "trustkeeper-go/app/service/wallet_management/pkg/service"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initGRPCHandler(endpoints, g)
	return g
}
func defaultGRPCOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]grpc.ServerOption {
	options := map[string][]grpc.ServerOption{
		"AssignedXpubToGroup":             {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "AssignedXpubToGroup", logger))},
		"CreateChain":                     {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "CreateChain", logger))},
		"CreateWallet":                    {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "CreateWallet", logger))},
		"GetChains":                       {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "GetChains", logger))},
		"GetWallets":                      {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "GetWallets", logger))},
		"QueryWalletHD":                   {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "QueryWalletHD", logger))},
		"QueryWalletsForGroupByChainName": {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "QueryWalletsForGroupByChainName", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["GetChains"] = []endpoint1.Middleware{
		endpoint.LoggingMiddleware(log.With(logger, "method", "GetChains")),
		endpoint.InstrumentingMiddleware(duration.With("method", "GetChains")),
	}
	mw["CreateChain"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "CreateChain")), endpoint.InstrumentingMiddleware(duration.With("method", "CreateChain"))}
	mw["AssignedXpubToGroup"] = []endpoint1.Middleware{
		endpoint.LoggingMiddleware(log.With(logger, "method", "AssignedXpubToGroup")),
		endpoint.InstrumentingMiddleware(duration.With("method", "AssignedXpubToGroup")),
		endpoint.Hystrix("AssignedXpubToGroup", "Service currently unavailable", logger),
	}
	mw["CreateWallet"] = []endpoint1.Middleware{
		endpoint.LoggingMiddleware(log.With(logger, "method", "CreateWallet")),
		endpoint.InstrumentingMiddleware(duration.With("method", "CreateWallet")),
		endpoint.Hystrix("CreateWallet", "Service currently unavailable", logger),
	}
	mw["GetWallets"] = []endpoint1.Middleware{
		endpoint.LoggingMiddleware(log.With(logger, "method", "GetWallets")),
		endpoint.InstrumentingMiddleware(duration.With("method", "GetWallets")),
		endpoint.Hystrix("GetWallets", "Service currently unavailable", logger),
	}
	mw["QueryWalletsForGroupByChainName"] = []endpoint1.Middleware{
		endpoint.LoggingMiddleware(log.With(logger, "method", "QueryWalletsForGroupByChainName")),
		endpoint.InstrumentingMiddleware(duration.With("method", "QueryWalletsForGroupByChainName")),
		endpoint.Hystrix("QueryWalletsForGroupByChainName", "Service currently unavailable", logger),
	}
	mw["QueryWalletHD"] = []endpoint1.Middleware{
		endpoint.LoggingMiddleware(log.With(logger, "method", "QueryWalletHD")),
		endpoint.InstrumentingMiddleware(duration.With("method", "QueryWalletHD")),
		endpoint.Hystrix("QueryWalletHD", "Service currently unavailable", logger),
	}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"GetChains", "CreateChain", "AssignedXpubToGroup", "CreateWallet", "GetWallets", "QueryWalletsForGroupByChainName", "QueryWalletHD"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
